import { App, Checkbox, Form, Input, Modal, Select, Skeleton, Switch, Tooltip } from "antd";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { api, errorMessage, formErrors } from "../../api/client";
import type { LinkageEvent, LinkageObligation, ServiceLinkage } from "../../api/types";
import { useAuth } from "../../auth/AuthContext";
import { Button, Card, CapsLabel, Field, MutedChip, PageHeader } from "../../components/ui";
import { LINKAGE_TONE } from "../../design/wltStatus";

type Action = "resolution" | "submit" | "approve" | "return" | "reject" | "activate" | "obligation" | "cure" | "close";
const LABEL: Record<Action, string> = { resolution: "Record group resolution", submit: "Submit for approval", approve: "Approve", return: "Return for revision", reject: "Reject", activate: "Activate linkage", obligation: "Log obligation", cure: "Record cure", close: "Close linkage" };
const PATH: Record<Action, string> = { resolution: "resolution", submit: "submit", approve: "approve", return: "return", reject: "reject", activate: "activate", obligation: "obligations", cure: "cure", close: "close" };
const statusLabel = (status: string) => status ? status.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()) : "Started";
const formatDateTime = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

function EvidenceTimeline({ events }: { events: LinkageEvent[] }) {
  if (!events.length) return <div className="t-meta">No evidence has been recorded yet.</div>;
  return <ol style={{ listStyle: "none", margin: 0, padding: 0 }} aria-label="Linkage evidence history">{events.map((event, index) => {
    const obligation = event.gate_snapshot?.obligation;
    return <li key={event.id} style={{ display: "grid", gridTemplateColumns: "20px 1fr", gap: 10, paddingBottom: 18 }}><div aria-hidden style={{ position: "relative" }}><span style={{ display: "block", width: 10, height: 10, borderRadius: 10, background: "var(--green-500)", marginTop: 5 }} />{index < events.length - 1 && <span style={{ position: "absolute", top: 17, left: 4, bottom: -13, borderLeft: "1px solid var(--border)" }} />}</div><div><strong>{event.from_status === event.to_status ? "Activity recorded" : `${statusLabel(event.from_status)} → ${statusLabel(event.to_status)}`}</strong><div className="t-meta">{formatDateTime(event.occurred_at)}{event.actor_name ? ` · ${event.actor_name}` : ""}</div>{obligation && <div style={{ marginTop: 4 }}>{obligation.kind} · {obligation.reference} · {obligation.missed ? "Missed" : "Met"} · {obligation.outstanding ? "Outstanding" : "Settled"}</div>}{event.reason && <div style={{ marginTop: 4 }}>{event.reason}</div>}</div></li>;
  })}</ol>;
}

export default function LinkageDetailPage() {
  const { linkageId } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { message } = App.useApp();
  const [linkage, setLinkage] = useState<ServiceLinkage | null>(null); const [events, setEvents] = useState<LinkageEvent[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [action, setAction] = useState<Action | null>(null); const [form] = Form.useForm();
  const [obligations, setObligations] = useState<LinkageObligation[]>([]); const [obligationAction, setObligationAction] = useState<"settle" | "write-off" | "transfer" | null>(null); const [selectedObligation, setSelectedObligation] = useState<LinkageObligation | null>(null); const [obligationForm] = Form.useForm();
  const facilitator = ["WLT_FACILITATOR", "SYSTEM_ADMIN"].includes(user?.role ?? ""); const approver = ["WLT_WOREDA_OFFICER", "WLT_REGION_OFFICER", "WLT_FEDERAL_OFFICER", "SYSTEM_ADMIN"].includes(user?.role ?? "");
  const load = useCallback(async () => { if (!linkageId) return; setLoading(true); try { const [detail, history, obligationList] = await Promise.all([api.get<ServiceLinkage>(`/wlt/linkages/${linkageId}/`), api.get<LinkageEvent[]>(`/wlt/linkages/${linkageId}/events/`), api.get<LinkageObligation[]>(`/wlt/linkages/${linkageId}/obligations/`)]); setLinkage(detail.data); setEvents(history.data); setObligations(obligationList.data); } catch (error) { message.error(errorMessage(error, "Could not load this linkage.")); } finally { setLoading(false); } }, [linkageId, message]);
  useEffect(() => { void load(); }, [load]);
  const allowed = useMemo(() => { if (!linkage) return []; const result: Action[] = []; if (facilitator && ["SCREENED", "BLOCKED", "RETURNED"].includes(linkage.status)) result.push("resolution"); if (facilitator && ["SCREENED", "BLOCKED"].includes(linkage.status)) result.push("submit"); if (approver && linkage.status === "PENDING_APPROVAL" && linkage.can_current_user_approve) result.push("approve", "return", "reject"); if (facilitator && linkage.status === "APPROVED") result.push("activate"); if (facilitator && ["ACTIVE", "DISTRESSED"].includes(linkage.status)) result.push("obligation"); if (facilitator && linkage.status === "DISTRESSED" && !linkage.terms?.outstanding_obligation) result.push("cure"); if (facilitator && ["ACTIVE", "DISTRESSED"].includes(linkage.status)) result.push("close"); return result; }, [approver, facilitator, linkage]);
  async function perform(values: Record<string, unknown>) { if (!linkage || !action) return; setSaving(true); try { await api.post(`/wlt/linkages/${linkage.id}/${PATH[action]}/`, values); message.success(`${LABEL[action]} completed.`); setAction(null); form.resetFields(); await load(); } catch (error) { const fields = formErrors(error); if (fields.length) form.setFields(fields); message.error(errorMessage(error, `Could not ${LABEL[action].toLowerCase()}.`)); } finally { setSaving(false); } }
  async function rescreen() { if (!linkage) return; setSaving(true); try { await api.post(`/wlt/linkages/${linkage.id}/screen/`); message.success("Screening refreshed."); await load(); } catch (error) { message.error(errorMessage(error, "Could not refresh screening.")); } finally { setSaving(false); } }
  async function resolveObligation(values: { note?: string; transfer_reference?: string }) { if (!linkage || !selectedObligation || !obligationAction) return; setSaving(true); try { await api.post(`/wlt/linkages/${linkage.id}/obligations/${obligationAction}/`, { reference: selectedObligation.reference, ...values }); message.success(obligationAction === "settle" ? "Obligation settled." : obligationAction === "write-off" ? "Write-off recorded." : "Obligation transferred."); setObligationAction(null); setSelectedObligation(null); obligationForm.resetFields(); await load(); } catch (error) { const fields = formErrors(error); if (fields.length) obligationForm.setFields(fields); message.error(errorMessage(error, "Could not resolve this obligation.")); } finally { setSaving(false); } }
  if (loading) return <div className="page stack"><Skeleton active /><Skeleton active /></div>;
  if (!linkage) return <div className="page stack"><PageHeader title="Linkage not found" /><Button onClick={() => navigate("/wlt/linkages")}>Back to linkages</Button></div>;
  const tone = LINKAGE_TONE[linkage.status];
  const eventDate = (status: string, fallback: string | null) => events.find((event) => event.to_status === status)?.occurred_at || fallback;
  return <div className="page stack">
    <div><Button onClick={() => navigate("/wlt/linkages")}>← Back to service linkages</Button></div>
    <PageHeader title={linkage.type_label} subtitle={<span>{linkage.subject_name || "Unknown subject"} · <span className="chip" style={{ color: tone.fg, background: tone.bg, borderColor: tone.bd }}><span className="chip__mark" aria-hidden>{tone.mark}</span>{linkage.status_display}</span></span>} />
    <Card><CapsLabel>Linkage overview</CapsLabel><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 18, marginTop: 12 }}><Field label="Subject">{linkage.subject_group ? <Link to={`/wlt/groups/${linkage.subject_group}`}>{linkage.subject_name || "View group"}</Link> : linkage.subject_name || "—"}</Field><Field label="Provider">{linkage.provider_name || "Not assigned"}</Field><Field label="Opened">{eventDate("PROPOSED", linkage.opened_on) ? formatDateTime(eventDate("PROPOSED", linkage.opened_on) as string) : "Not recorded"}</Field><Field label="Estimated value">{linkage.value_etb ? `${linkage.value_etb} ETB` : "Not recorded"}</Field><Field label="Approved">{eventDate("APPROVED", linkage.approved_on) ? formatDateTime(eventDate("APPROVED", linkage.approved_on) as string) : "Not yet"}</Field><Field label="Activated">{eventDate("ACTIVE", linkage.activated_on) ? formatDateTime(eventDate("ACTIVE", linkage.activated_on) as string) : "Not yet"}</Field></div></Card>
    {linkage.block_reasons.length > 0 && ["BLOCKED", "PENDING_APPROVAL"].includes(linkage.status) && <Card><CapsLabel>{linkage.status === "PENDING_APPROVAL" ? "Exception under review" : "Conditions to resolve"}</CapsLabel><ul>{linkage.block_reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>{linkage.status === "BLOCKED" && <Button disabled={saving} onClick={() => void rescreen()}>Re-screen now</Button>}</Card>}
    <Card><CapsLabel>Decision & obligation safeguards</CapsLabel><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}><MutedChip>{linkage.terms?.resolution_reference ? `Resolution ${String(linkage.terms.resolution_reference)}` : "Resolution not recorded"}</MutedChip><MutedChip>{linkage.terms?.outstanding_obligation ? "Outstanding obligation" : "No outstanding obligation recorded"}</MutedChip>{linkage.next_action_role_display && <MutedChip>Waiting for {linkage.next_action_role_display}</MutedChip>}</div></Card>
    <Card><CapsLabel>Obligations</CapsLabel>{obligations.length === 0 ? <p className="t-meta">No obligations have been logged.</p> : <div className="stack" style={{ marginTop: 10 }}>{obligations.map((obligation) => <div key={obligation.reference} style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", borderBottom: "1px solid var(--border)", paddingBottom: 10 }}><div><strong>{obligation.kind} · {obligation.reference}</strong><div className="t-meta">{formatDateTime(obligation.occurred_at)} · {obligation.missed ? "Missed" : "Met"} · {obligation.outstanding ? "Outstanding" : obligation.resolution ? obligation.resolution.replace("_", " ").toLowerCase() : "Settled"}</div>{obligation.note && <div>{obligation.note}</div>}</div>{obligation.outstanding && <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}><Button size="sm" onClick={() => { setSelectedObligation(obligation); setObligationAction("settle"); }}>Settle</Button>{approver && <Button size="sm" onClick={() => { setSelectedObligation(obligation); setObligationAction("write-off"); }}>Write off</Button>}<Button size="sm" onClick={() => { setSelectedObligation(obligation); setObligationAction("transfer"); }}>Transfer</Button></div>}</div>)}</div>}</Card>
    <Card><CapsLabel>Available actions</CapsLabel>{allowed.length ? <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>{allowed.map((item, index) => { const blocker = item === "close" ? obligations.find((row) => row.outstanding) : undefined; return <Tooltip key={item} title={blocker ? `Settle, write off, or transfer ${blocker.kind} ${blocker.reference} before closing.` : undefined}><span><Button variant={index === 0 ? "primary" : item === "close" ? "destructive-soft" : "secondary"} disabled={Boolean(blocker)} onClick={() => { form.resetFields(); setAction(item); }}>{LABEL[item]}</Button></span></Tooltip>; })}</div> : <div className="t-meta" style={{ marginTop: 8 }}>No action is available for your role at this stage.</div>}</Card>
    <Card><CapsLabel style={{ marginBottom: 12 }}>Evidence & immutable history</CapsLabel><EvidenceTimeline events={events} /></Card>
    <Modal open={Boolean(action)} onCancel={() => setAction(null)} title={action ? LABEL[action] : ""} okText={action === "approve" ? "Approve" : action === "close" ? "Close linkage" : "Save"} onOk={() => form.submit()} confirmLoading={saving} destroyOnHidden><Form form={form} layout="vertical" onFinish={(values) => void perform(values)} initialValues={action === "obligation" ? { outstanding: true, missed: false } : undefined}>
      {action === "resolution" && <><Form.Item name="reference" label="Minute-book resolution reference" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="meeting_id" label="Digital meeting ID (optional)"><Input /></Form.Item></>}{action === "submit" && linkage.status === "BLOCKED" && <Form.Item name="override_reason" label="Override reason" extra="Adds another approval level. Credit minimum phase cannot be overridden." rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item>}{action === "approve" && <Form.Item name="note" label="Decision note"><Input.TextArea rows={3} /></Form.Item>}{["return", "reject"].includes(action || "") && <Form.Item name="reason" label={action === "return" ? "What must be corrected?" : "Rejection reason"} rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item>}{action === "activate" && <Form.Item name={["terms", "reference"]} label="Provider agreement / account reference" rules={[{ required: true }]}><Input /></Form.Item>}
      {action === "submit" && linkage.status !== "BLOCKED" && <p>This sends the linkage and its evidence to the first configured approver. It cannot be edited while approval is pending.</p>}
      {action === "obligation" && <><Form.Item name="kind" label="Obligation type" rules={[{ required: true }]}><Select options={["Payment", "Repayment", "Deposit", "Delivery"].map((item) => ({ value: item.toLowerCase(), label: item }))} /></Form.Item><Form.Item name="reference" label="Reference" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="missed" valuePropName="checked"><Checkbox>Obligation was missed</Checkbox></Form.Item><Form.Item name="outstanding" label="Still outstanding" valuePropName="checked"><Switch /></Form.Item><Form.Item name="note" label="Evidence note"><Input.TextArea rows={2} /></Form.Item></>}{action === "cure" && <Form.Item name="note" label="Cure evidence note" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item>}{action === "close" && <><p className="t-meta">Closure is refused while an obligation is outstanding.</p><Form.Item name="reason" label="Closure reason" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item></>}
    </Form></Modal>
    <Modal open={Boolean(obligationAction)} onCancel={() => { setObligationAction(null); setSelectedObligation(null); }} title={obligationAction === "settle" ? "Settle obligation" : obligationAction === "write-off" ? "Write off obligation" : "Transfer obligation"} onOk={() => obligationForm.submit()} confirmLoading={saving} okText={obligationAction === "settle" ? "Settle" : obligationAction === "write-off" ? "Write off" : "Transfer"} destroyOnHidden><p>{selectedObligation?.kind} · {selectedObligation?.reference}</p><Form form={obligationForm} layout="vertical" onFinish={(values) => void resolveObligation(values)}>{obligationAction === "write-off" && <Form.Item name="note" label="Approval note" rules={[{ required: true, message: "Record the approver's reason." }]}><Input.TextArea rows={3} /></Form.Item>}{obligationAction === "transfer" && <><Form.Item name="transfer_reference" label="Receiving obligation reference" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="note" label="Transfer note"><Input.TextArea rows={2} /></Form.Item></>}{obligationAction === "settle" && <Form.Item name="note" label="Settlement note"><Input.TextArea rows={2} /></Form.Item>}</Form></Modal>
  </div>;
}
