import { App, Checkbox, Form, Input, Modal, Select, Skeleton, Switch } from "antd";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { api, errorMessage } from "../../api/client";
import type { LinkageEvent, ServiceLinkage } from "../../api/types";
import { useAuth } from "../../auth/AuthContext";
import { Button, Card, CapsLabel, Field, MutedChip, PageHeader } from "../../components/ui";
import { LINKAGE_TONE } from "../../design/wltStatus";

type Action = "resolution" | "submit" | "approve" | "return" | "reject" | "activate" | "obligation" | "cure" | "close";
const LABEL: Record<Action, string> = { resolution: "Record group resolution", submit: "Submit for approval", approve: "Approve", return: "Return for revision", reject: "Reject", activate: "Activate linkage", obligation: "Log obligation", cure: "Record cure", close: "Close linkage" };
const PATH: Record<Action, string> = { resolution: "resolution", submit: "submit", approve: "approve", return: "return", reject: "reject", activate: "activate", obligation: "obligations", cure: "cure", close: "close" };

function EvidenceTimeline({ events }: { events: LinkageEvent[] }) {
  if (!events.length) return <div className="t-meta">No evidence has been recorded yet.</div>;
  return <ol style={{ listStyle: "none", margin: 0, padding: 0 }} aria-label="Linkage evidence history">{events.map((event, index) => {
    const obligation = event.gate_snapshot?.obligation;
    return <li key={event.id} style={{ display: "grid", gridTemplateColumns: "20px 1fr", gap: 10, paddingBottom: 18 }}><div aria-hidden style={{ position: "relative" }}><span style={{ display: "block", width: 10, height: 10, borderRadius: 10, background: "var(--green-500)", marginTop: 5 }} />{index < events.length - 1 && <span style={{ position: "absolute", top: 17, left: 4, bottom: -13, borderLeft: "1px solid var(--border)" }} />}</div><div><strong>{event.from_status === event.to_status ? "Activity recorded" : `${event.from_status || "Started"} → ${event.to_status}`}</strong><div className="t-meta">{new Date(event.occurred_at).toLocaleString()}{event.actor_name ? ` · ${event.actor_name}` : ""}</div>{obligation && <div style={{ marginTop: 4 }}>{obligation.kind} · {obligation.reference} · {obligation.missed ? "Missed" : "Met"} · {obligation.outstanding ? "Outstanding" : "Settled"}</div>}{event.reason && <div style={{ marginTop: 4 }}>{event.reason}</div>}</div></li>;
  })}</ol>;
}

export default function LinkageDetailPage() {
  const { linkageId } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { message } = App.useApp();
  const [linkage, setLinkage] = useState<ServiceLinkage | null>(null); const [events, setEvents] = useState<LinkageEvent[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [action, setAction] = useState<Action | null>(null); const [form] = Form.useForm();
  const facilitator = ["WLT_FACILITATOR", "SYSTEM_ADMIN"].includes(user?.role ?? ""); const approver = ["WLT_WOREDA_OFFICER", "WLT_REGION_OFFICER", "WLT_FEDERAL_OFFICER", "SYSTEM_ADMIN"].includes(user?.role ?? "");
  const load = useCallback(async () => { if (!linkageId) return; setLoading(true); try { const [detail, history] = await Promise.all([api.get<ServiceLinkage>(`/wlt/linkages/${linkageId}/`), api.get<LinkageEvent[]>(`/wlt/linkages/${linkageId}/events/`)]); setLinkage(detail.data); setEvents(history.data); } catch (error) { message.error(errorMessage(error, "Could not load this linkage.")); } finally { setLoading(false); } }, [linkageId, message]);
  useEffect(() => { void load(); }, [load]);
  const allowed = useMemo(() => { if (!linkage) return []; const result: Action[] = []; if (facilitator && ["SCREENED", "BLOCKED", "RETURNED"].includes(linkage.status)) result.push("resolution"); if (facilitator && ["SCREENED", "BLOCKED"].includes(linkage.status)) result.push("submit"); if (approver && linkage.status === "PENDING_APPROVAL" && linkage.can_current_user_approve) result.push("approve", "return", "reject"); if (facilitator && linkage.status === "APPROVED") result.push("activate"); if (facilitator && ["ACTIVE", "DISTRESSED"].includes(linkage.status)) result.push("obligation"); if (facilitator && linkage.status === "DISTRESSED" && !linkage.terms?.outstanding_obligation) result.push("cure"); if (facilitator && ["ACTIVE", "DISTRESSED"].includes(linkage.status)) result.push("close"); return result; }, [approver, facilitator, linkage]);
  async function perform(values: Record<string, unknown>) { if (!linkage || !action) return; setSaving(true); try { await api.post(`/wlt/linkages/${linkage.id}/${PATH[action]}/`, values); message.success(`${LABEL[action]} completed.`); setAction(null); form.resetFields(); await load(); } catch (error) { message.error(errorMessage(error, `Could not ${LABEL[action].toLowerCase()}.`)); } finally { setSaving(false); } }
  async function rescreen() { if (!linkage) return; setSaving(true); try { await api.post(`/wlt/linkages/${linkage.id}/screen/`); message.success("Screening refreshed."); await load(); } catch (error) { message.error(errorMessage(error, "Could not refresh screening.")); } finally { setSaving(false); } }
  if (loading) return <div className="page stack"><Skeleton active /><Skeleton active /></div>;
  if (!linkage) return <div className="page stack"><PageHeader title="Linkage not found" /><Button onClick={() => navigate("/wlt/linkages")}>Back to linkages</Button></div>;
  const tone = LINKAGE_TONE[linkage.status];
  return <div className="page stack">
    <div><Button onClick={() => navigate("/wlt/linkages")}>← Back to service linkages</Button></div>
    <PageHeader title={linkage.type_label} subtitle={<span>{linkage.subject_name || "Unknown subject"} · <span className="chip" style={{ color: tone.fg, background: tone.bg, borderColor: tone.bd }}><span className="chip__mark" aria-hidden>{tone.mark}</span>{linkage.status_display}</span></span>} />
    <Card><CapsLabel>Linkage overview</CapsLabel><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 18, marginTop: 12 }}><Field label="Subject">{linkage.subject_group ? <Link to={`/wlt/groups/${linkage.subject_group}`}>{linkage.subject_name || "View group"}</Link> : linkage.subject_name || "—"}</Field><Field label="Provider">{linkage.provider_name || "Not assigned"}</Field><Field label="Opened">{linkage.opened_on}</Field><Field label="Estimated value">{linkage.value_etb ? `${linkage.value_etb} ETB` : "Not recorded"}</Field><Field label="Approved">{linkage.approved_on || "Not yet"}</Field><Field label="Activated">{linkage.activated_on || "Not yet"}</Field></div></Card>
    {linkage.block_reasons.length > 0 && ["BLOCKED", "PENDING_APPROVAL"].includes(linkage.status) && <Card><CapsLabel>{linkage.status === "PENDING_APPROVAL" ? "Exception under review" : "Conditions to resolve"}</CapsLabel><ul>{linkage.block_reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>{linkage.status === "BLOCKED" && <Button disabled={saving} onClick={() => void rescreen()}>Re-screen now</Button>}</Card>}
    <Card><CapsLabel>Decision & obligation safeguards</CapsLabel><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}><MutedChip>{linkage.terms?.resolution_reference ? `Resolution ${String(linkage.terms.resolution_reference)}` : "Resolution not recorded"}</MutedChip><MutedChip>{linkage.terms?.outstanding_obligation ? "Outstanding obligation" : "No outstanding obligation recorded"}</MutedChip>{linkage.status === "PENDING_APPROVAL" && linkage.next_approval_role && <MutedChip>Waiting for {linkage.next_approval_role.replaceAll("_", " ").toLowerCase()}</MutedChip>}</div></Card>
    <Card><CapsLabel>Available actions</CapsLabel>{allowed.length ? <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>{allowed.map((item, index) => <Button key={item} variant={index === 0 ? "primary" : item === "close" ? "destructive-soft" : "secondary"} onClick={() => { form.resetFields(); setAction(item); }}>{LABEL[item]}</Button>)}</div> : <div className="t-meta" style={{ marginTop: 8 }}>No action is available for your role at this stage.</div>}</Card>
    <Card><CapsLabel style={{ marginBottom: 12 }}>Evidence & immutable history</CapsLabel><EvidenceTimeline events={events} /></Card>
    <Modal open={Boolean(action)} onCancel={() => setAction(null)} title={action ? LABEL[action] : ""} okText={action === "approve" ? "Approve" : action === "close" ? "Close linkage" : "Save"} onOk={() => form.submit()} confirmLoading={saving} destroyOnHidden><Form form={form} layout="vertical" onFinish={(values) => void perform(values)} initialValues={action === "obligation" ? { outstanding: true, missed: false } : undefined}>
      {action === "resolution" && <><Form.Item name="reference" label="Minute-book resolution reference" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="meeting_id" label="Digital meeting ID (optional)"><Input /></Form.Item></>}{action === "submit" && linkage.status === "BLOCKED" && <Form.Item name="override_reason" label="Override reason" extra="Adds another approval level. Credit minimum phase cannot be overridden." rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item>}{action === "approve" && <Form.Item name="note" label="Decision note"><Input.TextArea rows={3} /></Form.Item>}{["return", "reject"].includes(action || "") && <Form.Item name="reason" label={action === "return" ? "What must be corrected?" : "Rejection reason"} rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item>}{action === "activate" && <Form.Item name={["terms", "reference"]} label="Provider agreement / account reference" rules={[{ required: true }]}><Input /></Form.Item>}
      {action === "obligation" && <><Form.Item name="kind" label="Obligation type" rules={[{ required: true }]}><Select options={["Payment", "Repayment", "Deposit", "Delivery"].map((item) => ({ value: item.toLowerCase(), label: item }))} /></Form.Item><Form.Item name="reference" label="Reference" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="missed" valuePropName="checked"><Checkbox>Obligation was missed</Checkbox></Form.Item><Form.Item name="outstanding" label="Still outstanding" valuePropName="checked"><Switch /></Form.Item><Form.Item name="note" label="Evidence note"><Input.TextArea rows={2} /></Form.Item></>}{action === "cure" && <Form.Item name="note" label="Cure evidence note" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item>}{action === "close" && <><p className="t-meta">Closure is refused while an obligation is outstanding.</p><Form.Item name="reason" label="Closure reason" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item></>}
    </Form></Modal>
  </div>;
}
