# Generated by Django 5.2.17 on 2026-08-11 00:18

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("youth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCase",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STALLED", "Stalled"),
                            ("REFERRAL_PENDING", "Referral Pending"),
                            ("PLACED", "Placed"),
                            ("EXITED", "Exited"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="case status",
                    ),
                ),
                ("woreda", models.CharField(db_index=True, max_length=128, verbose_name="woreda")),
                (
                    "opened_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="opened date"),
                ),
                ("closed_date", models.DateField(blank=True, null=True, verbose_name="closed date")),
                ("exit_reason", models.TextField(blank=True, verbose_name="exit reason")),
                (
                    "last_activity_date",
                    models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                        help_text="System updated on any case event. Drives the stall alert.",
                        verbose_name="last activity date",
                    ),
                ),
                ("next_action", models.TextField(blank=True, verbose_name="next action")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case_manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Currently assigned case manager.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="case manager",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_action_owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="next action owner",
                    ),
                ),
                (
                    "youth",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="youth.youth",
                        verbose_name="youth",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical case",
                "verbose_name_plural": "historical cases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STALLED", "Stalled"),
                            ("REFERRAL_PENDING", "Referral Pending"),
                            ("PLACED", "Placed"),
                            ("EXITED", "Exited"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="case status",
                    ),
                ),
                ("woreda", models.CharField(db_index=True, max_length=128, verbose_name="woreda")),
                (
                    "opened_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="opened date"),
                ),
                ("closed_date", models.DateField(blank=True, null=True, verbose_name="closed date")),
                ("exit_reason", models.TextField(blank=True, verbose_name="exit reason")),
                (
                    "last_activity_date",
                    models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                        help_text="System updated on any case event. Drives the stall alert.",
                        verbose_name="last activity date",
                    ),
                ),
                ("next_action", models.TextField(blank=True, verbose_name="next action")),
                (
                    "case_manager",
                    models.ForeignKey(
                        help_text="Currently assigned case manager.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="case manager",
                    ),
                ),
                (
                    "next_action_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_next_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="next action owner",
                    ),
                ),
                (
                    "youth",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case",
                        to="youth.youth",
                        verbose_name="youth",
                    ),
                ),
            ],
            options={
                "verbose_name": "case",
                "verbose_name_plural": "cases",
                "ordering": ["-last_activity_date"],
                "indexes": [
                    models.Index(fields=["woreda", "case_status"], name="cases_case_woreda_8276bc_idx"),
                    models.Index(fields=["case_manager", "case_status"], name="cases_case_case_ma_9786e5_idx"),
                    models.Index(fields=["last_activity_date"], name="cases_case_last_ac_a2a655_idx"),
                ],
            },
        ),
    ]
