# Generated by Django 5.2.17 on 2026-08-11 02:32

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProfilingRecord",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("work_history_summary", models.TextField(blank=True, verbose_name="work history summary")),
                (
                    "skills_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="skills",
                    ),
                ),
                (
                    "vulnerability_index_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Methodology pending definition with M&E (spec §11).",
                        max_digits=6,
                        null=True,
                        verbose_name="vulnerability index score",
                    ),
                ),
                (
                    "eligibility_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("WAGE_EMPLOYMENT", "Wage Employment"),
                                ("SELF_EMPLOYMENT", "Self-Employment"),
                                ("APPRENTICESHIP", "Apprenticeship"),
                                ("TRAINING", "Training"),
                            ],
                            max_length=32,
                        ),
                        default=list,
                        help_text="Pathways this youth is eligible for.",
                        size=None,
                        verbose_name="eligibility flags",
                    ),
                ),
                (
                    "priority_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Marks a high-vulnerability case for priority handling.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "assessed_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="assessed date"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assessor",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical profiling and eligibility record",
                "verbose_name_plural": "historical profiling and eligibility records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PathwayAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("assessed_interests", models.TextField(blank=True, verbose_name="assessed interests")),
                ("capacities", models.TextField(blank=True, verbose_name="capacities")),
                ("barriers", models.TextField(blank=True, verbose_name="barriers")),
                (
                    "selected_pathway",
                    models.CharField(
                        choices=[
                            ("WAGE_EMPLOYMENT", "Wage Employment"),
                            ("SELF_EMPLOYMENT", "Self-Employment"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("TRAINING", "Training"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="selected pathway",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="assessment date"),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True, verbose_name="is current")),
                ("revision_reason", models.TextField(blank=True, verbose_name="revision reason")),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathway_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assessor",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathway_assignments",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="cases.pathwayassignment",
                        verbose_name="superseded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "pathway assignment",
                "verbose_name_plural": "pathway assignments",
                "ordering": ["-assessment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPathwayAssignment",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("assessed_interests", models.TextField(blank=True, verbose_name="assessed interests")),
                ("capacities", models.TextField(blank=True, verbose_name="capacities")),
                ("barriers", models.TextField(blank=True, verbose_name="barriers")),
                (
                    "selected_pathway",
                    models.CharField(
                        choices=[
                            ("WAGE_EMPLOYMENT", "Wage Employment"),
                            ("SELF_EMPLOYMENT", "Self-Employment"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("TRAINING", "Training"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="selected pathway",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="assessment date"),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True, verbose_name="is current")),
                ("revision_reason", models.TextField(blank=True, verbose_name="revision reason")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assessor",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.pathwayassignment",
                        verbose_name="superseded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pathway assignment",
                "verbose_name_plural": "historical pathway assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="case",
            name="current_pathway_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cases.pathwayassignment",
                verbose_name="current pathway assignment",
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="current_pathway_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cases.pathwayassignment",
                verbose_name="current pathway assignment",
            ),
        ),
        migrations.CreateModel(
            name="ProfilingRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("work_history_summary", models.TextField(blank=True, verbose_name="work history summary")),
                (
                    "skills_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="skills",
                    ),
                ),
                (
                    "vulnerability_index_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Methodology pending definition with M&E (spec §11).",
                        max_digits=6,
                        null=True,
                        verbose_name="vulnerability index score",
                    ),
                ),
                (
                    "eligibility_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("WAGE_EMPLOYMENT", "Wage Employment"),
                                ("SELF_EMPLOYMENT", "Self-Employment"),
                                ("APPRENTICESHIP", "Apprenticeship"),
                                ("TRAINING", "Training"),
                            ],
                            max_length=32,
                        ),
                        default=list,
                        help_text="Pathways this youth is eligible for.",
                        size=None,
                        verbose_name="eligibility flags",
                    ),
                ),
                (
                    "priority_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Marks a high-vulnerability case for priority handling.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "assessed_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="assessed date"),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiling_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assessor",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling_records",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
            ],
            options={
                "verbose_name": "profiling and eligibility record",
                "verbose_name_plural": "profiling and eligibility records",
                "ordering": ["-assessed_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pathwayassignment",
            index=models.Index(fields=["case", "-assessment_date"], name="cases_pathw_case_id_829dc2_idx"),
        ),
        migrations.AddConstraint(
            model_name="pathwayassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)), fields=("case",), name="one_current_pathway_per_case"
            ),
        ),
        migrations.AddIndex(
            model_name="profilingrecord",
            index=models.Index(fields=["case", "-assessed_date"], name="cases_profi_case_id_b90799_idx"),
        ),
    ]
