# Generated by Django 5.2.17 on 2026-08-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_caseaction"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="caseaction",
            new_name="cases_casea_case_id_c274c3_idx",
            old_name="cases_casea_case_id_13098e_idx",
        ),
        migrations.RenameIndex(
            model_name="caseaction",
            new_name="cases_casea_created_ae0f87_idx",
            old_name="cases_casea_created_610b45_idx",
        ),
    ]
