# Generated by Django 5.2.17 on 2026-08-11 00:18

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalYouth",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("full_name", models.CharField(db_index=True, max_length=255, verbose_name="full name")),
                (
                    "sex",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                        max_length=8,
                        verbose_name="sex",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Used to confirm youth age band eligibility.", verbose_name="date of birth"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Youth or next-of-kin contact.",
                        max_length=32,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "national_or_kebele_id",
                    models.CharField(
                        blank=True,
                        help_text="Local identification, where available.",
                        max_length=64,
                        verbose_name="national or kebele ID",
                    ),
                ),
                ("region", models.CharField(max_length=128, verbose_name="region")),
                ("zone", models.CharField(max_length=128, verbose_name="zone")),
                ("woreda", models.CharField(db_index=True, max_length=128, verbose_name="woreda")),
                ("kebele", models.CharField(max_length=128, verbose_name="kebele")),
                (
                    "household_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifier in the PSNP household registration system, where the youth is linked to one.",
                        max_length=64,
                        verbose_name="PSNP household ID",
                    ),
                ),
                (
                    "psnp_status",
                    models.CharField(
                        blank=True,
                        choices=[("ENROLLED", "Enrolled"), ("GRADUATED", "Graduated"), ("NOT_PSNP", "Not PSNP")],
                        db_index=True,
                        max_length=16,
                        verbose_name="PSNP status",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "No formal education"),
                            ("PRIMARY_INCOMPLETE", "Primary incomplete (grades 1-8)"),
                            ("PRIMARY_COMPLETE", "Primary complete (grade 8)"),
                            ("SECONDARY_INCOMPLETE", "Secondary incomplete (grades 9-12)"),
                            ("SECONDARY_COMPLETE", "Secondary complete (grade 12)"),
                            ("TVET", "TVET certificate or diploma"),
                            ("TERTIARY", "University degree or above"),
                        ],
                        max_length=24,
                        verbose_name="education level",
                    ),
                ),
                (
                    "disability_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "No disability"),
                            ("PHYSICAL", "Physical / mobility"),
                            ("VISUAL", "Visual"),
                            ("HEARING", "Hearing"),
                            ("INTELLECTUAL", "Intellectual"),
                            ("PSYCHOSOCIAL", "Psychosocial"),
                            ("MULTIPLE", "Multiple"),
                            ("UNDISCLOSED", "Not disclosed"),
                        ],
                        max_length=16,
                        verbose_name="disability status",
                    ),
                ),
                ("consent_given", models.BooleanField(default=False, verbose_name="consent given")),
                ("consent_date", models.DateField(blank=True, null=True, verbose_name="consent date")),
                (
                    "registration_date",
                    models.DateField(blank=True, db_index=True, editable=False, verbose_name="registration date"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registering_worker",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Outreach worker or facilitator who registered the youth.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registering worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical youth",
                "verbose_name_plural": "historical youth",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Youth",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("full_name", models.CharField(db_index=True, max_length=255, verbose_name="full name")),
                (
                    "sex",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                        max_length=8,
                        verbose_name="sex",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Used to confirm youth age band eligibility.", verbose_name="date of birth"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Youth or next-of-kin contact.",
                        max_length=32,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "national_or_kebele_id",
                    models.CharField(
                        blank=True,
                        help_text="Local identification, where available.",
                        max_length=64,
                        verbose_name="national or kebele ID",
                    ),
                ),
                ("region", models.CharField(max_length=128, verbose_name="region")),
                ("zone", models.CharField(max_length=128, verbose_name="zone")),
                ("woreda", models.CharField(db_index=True, max_length=128, verbose_name="woreda")),
                ("kebele", models.CharField(max_length=128, verbose_name="kebele")),
                (
                    "household_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifier in the PSNP household registration system, where the youth is linked to one.",
                        max_length=64,
                        verbose_name="PSNP household ID",
                    ),
                ),
                (
                    "psnp_status",
                    models.CharField(
                        blank=True,
                        choices=[("ENROLLED", "Enrolled"), ("GRADUATED", "Graduated"), ("NOT_PSNP", "Not PSNP")],
                        db_index=True,
                        max_length=16,
                        verbose_name="PSNP status",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "No formal education"),
                            ("PRIMARY_INCOMPLETE", "Primary incomplete (grades 1-8)"),
                            ("PRIMARY_COMPLETE", "Primary complete (grade 8)"),
                            ("SECONDARY_INCOMPLETE", "Secondary incomplete (grades 9-12)"),
                            ("SECONDARY_COMPLETE", "Secondary complete (grade 12)"),
                            ("TVET", "TVET certificate or diploma"),
                            ("TERTIARY", "University degree or above"),
                        ],
                        max_length=24,
                        verbose_name="education level",
                    ),
                ),
                (
                    "disability_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "No disability"),
                            ("PHYSICAL", "Physical / mobility"),
                            ("VISUAL", "Visual"),
                            ("HEARING", "Hearing"),
                            ("INTELLECTUAL", "Intellectual"),
                            ("PSYCHOSOCIAL", "Psychosocial"),
                            ("MULTIPLE", "Multiple"),
                            ("UNDISCLOSED", "Not disclosed"),
                        ],
                        max_length=16,
                        verbose_name="disability status",
                    ),
                ),
                ("consent_given", models.BooleanField(default=False, verbose_name="consent given")),
                ("consent_date", models.DateField(blank=True, null=True, verbose_name="consent date")),
                (
                    "registration_date",
                    models.DateField(auto_now_add=True, db_index=True, verbose_name="registration date"),
                ),
                (
                    "registering_worker",
                    models.ForeignKey(
                        help_text="Outreach worker or facilitator who registered the youth.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_youth",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registering worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "youth",
                "verbose_name_plural": "youth",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["woreda", "full_name"], name="youth_youth_woreda_27755e_idx"),
                    models.Index(fields=["registration_date"], name="youth_youth_registr_f0167d_idx"),
                ],
            },
        ),
    ]
