# Generated by Django 5.2.17 on 2026-08-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalyouth",
            name="settlement_type",
            field=models.CharField(
                blank=True,
                choices=[("RURAL", "Rural"), ("PERI_URBAN", "Peri-urban"), ("URBAN", "Urban")],
                db_index=True,
                help_text="Rural, peri-urban or urban. Required by the ILO and World Bank disaggregation.",
                max_length=16,
                verbose_name="settlement type",
            ),
        ),
        migrations.AddField(
            model_name="youth",
            name="settlement_type",
            field=models.CharField(
                blank=True,
                choices=[("RURAL", "Rural"), ("PERI_URBAN", "Peri-urban"), ("URBAN", "Urban")],
                db_index=True,
                help_text="Rural, peri-urban or urban. Required by the ILO and World Bank disaggregation.",
                max_length=16,
                verbose_name="settlement type",
            ),
        ),
    ]
