# Generated by Django 5.2.17 on 2026-08-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youth", "0002_historicalyouth_settlement_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalyouth",
            name="psnp_client_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC_WORKS", "Public works"),
                    ("PERMANENT_DIRECT_SUPPORT", "Permanent direct support"),
                    ("TEMPORARY_DIRECT_SUPPORT", "Temporary direct support"),
                ],
                db_index=True,
                help_text="Public works or direct support. Needed to report a placement against the right caseload.",
                max_length=32,
                verbose_name="PSNP client category",
            ),
        ),
        migrations.AddField(
            model_name="youth",
            name="psnp_client_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC_WORKS", "Public works"),
                    ("PERMANENT_DIRECT_SUPPORT", "Permanent direct support"),
                    ("TEMPORARY_DIRECT_SUPPORT", "Temporary direct support"),
                ],
                db_index=True,
                help_text="Public works or direct support. Needed to report a placement against the right caseload.",
                max_length=32,
                verbose_name="PSNP client category",
            ),
        ),
    ]
