"""Alert / Task — spec §4.13.

Alerts are generated by the system rules in §6, not created by hand. Each one
says: something on this case needs a person, and here is who. The detection jobs
in `tasks.py` are the only writers.

An alert is a *materialisation* of a condition that already exists in the data —
a case with no recent activity, a referral awaiting confirmation past its
window, a completed referral with no onward step. The condition remains the
source of truth (see the querysets in `apps.referrals.models` and
`apps.cases.models`); the alert exists so the condition lands in somebody's
inbox and its resolution is recorded.
"""

from datetime import date

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from apps.common.models import BaseModel


class AlertType(models.TextChoices):
    """Spec §4.13, verbatim."""

    STALL = "STALL", _("Stall Alert")
    REFERRAL_CONFIRMATION_OVERDUE = "REFERRAL_CONFIRMATION_OVERDUE", _("Referral Confirmation Overdue")
    FOLLOW_UP_DUE = "FOLLOW_UP_DUE", _("Follow-Up Due")
    ONWARD_REFERRAL_PROMPT = "ONWARD_REFERRAL_PROMPT", _("Onward Referral Prompt")
    REPLACEMENT_REFERRAL_PROMPT = "REPLACEMENT_REFERRAL_PROMPT", _("Replacement Referral Prompt")
    RETENTION_CHECK_DUE = "RETENTION_CHECK_DUE", _("Retention Check Due")

    @classmethod
    def referral_scoped(cls):
        """Types that concern one specific referral rather than the case at large."""
        return {cls.REFERRAL_CONFIRMATION_OVERDUE, cls.ONWARD_REFERRAL_PROMPT, cls.REPLACEMENT_REFERRAL_PROMPT}


class AlertStatus(models.TextChoices):
    """Spec §4.13: Open / Actioned / Dismissed."""

    OPEN = "OPEN", _("Open")
    ACTIONED = "ACTIONED", _("Actioned")
    DISMISSED = "DISMISSED", _("Dismissed")


# Default threshold per alert type, in days. §4.13 makes `threshold_days`
# "configurable per alert_type"; the settings below are the configuration point
# and the value in force is copied onto each alert row when it is raised, so a
# later change to the threshold does not rewrite history.
#
# TODO(open-question): spec §11 — "Set the caseload ceiling and stall-alert
# threshold_days defaults with programme management." These are placeholders.
def threshold_for(alert_type):
    return {
        AlertType.STALL: settings.STALL_ALERT_THRESHOLD_DAYS,
        AlertType.REFERRAL_CONFIRMATION_OVERDUE: settings.REFERRAL_CONFIRMATION_OVERDUE_DAYS,
        AlertType.FOLLOW_UP_DUE: settings.FOLLOW_UP_DUE_DAYS,
        AlertType.RETENTION_CHECK_DUE: settings.RETENTION_CHECK_DUE_DAYS,
        # Prompts fire on a state change, not after an elapsed period.
        AlertType.ONWARD_REFERRAL_PROMPT: 0,
        AlertType.REPLACEMENT_REFERRAL_PROMPT: 0,
    }.get(alert_type, 0)


class AlertQuerySet(models.QuerySet):
    def open(self):
        return self.filter(status=AlertStatus.OPEN)

    def for_user(self, user):
        return self.filter(assigned_to=user)

    def of_type(self, alert_type):
        return self.filter(alert_type=alert_type)


class Alert(BaseModel):
    """Spec §4.13. `alert_id` is `id`, per the §4 type-translation guide."""

    case = models.ForeignKey(
        "cases.Case",
        on_delete=models.CASCADE,
        related_name="alerts",
        verbose_name=_("case"),
    )

    # Not in the §4.13 field list, but three of its six alert types name a
    # referral ("Referral Confirmation Overdue", "Onward Referral Prompt",
    # "Replacement Referral Prompt"). Without this a case with two completed
    # referrals could raise only one onward prompt, and a case manager could not
    # tell which referral it meant. Nullable: stall alerts concern the case.
    referral = models.ForeignKey(
        "referrals.Referral",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="alerts",
        verbose_name=_("referral"),
    )

    alert_type = models.CharField(_("alert type"), max_length=32, choices=AlertType.choices, db_index=True)

    triggered_date = models.DateField(_("triggered date"), default=date.today, db_index=True)
    threshold_days = models.PositiveSmallIntegerField(
        _("threshold days"),
        default=0,
        help_text=_("The threshold in force when this alert was raised. Configurable per alert type."),
    )

    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="assigned_alerts",
        verbose_name=_("assigned to"),
    )

    status = models.CharField(
        _("status"), max_length=16, choices=AlertStatus.choices, default=AlertStatus.OPEN, db_index=True
    )
    actioned_date = models.DateField(_("actioned date"), null=True, blank=True)
    actioned_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="actioned_alerts",
        verbose_name=_("actioned by"),
    )

    # Not in §4.13. A short human-readable line so an inbox row is meaningful
    # without loading the case — "no activity for 47 days", "awaiting Adama
    # Polytechnic since 12 Aug". Generated by the detection job.
    summary = models.CharField(_("summary"), max_length=255, blank=True)

    history = HistoricalRecords()  # §9 audit trail

    objects = AlertQuerySet.as_manager()

    class Meta:
        verbose_name = _("alert")
        verbose_name_plural = _("alerts")
        ordering = ["-triggered_date", "-created_at"]
        constraints = [
            # The beat jobs re-run on a schedule and re-detect the same
            # conditions every time. Without this a stalled case would collect a
            # new alert on every run until someone noticed. A partial unique
            # index means the second insert is refused by the database rather
            # than relying on every job remembering to check first.
            models.UniqueConstraint(
                fields=["case", "alert_type", "referral"],
                condition=models.Q(status=AlertStatus.OPEN),
                name="one_open_alert_per_case_type_referral",
            ),
            # Postgres treats NULLs as distinct in a unique index, so the
            # constraint above does not cover case-level alerts (referral IS
            # NULL). This second one does.
            models.UniqueConstraint(
                fields=["case", "alert_type"],
                condition=models.Q(status=AlertStatus.OPEN, referral__isnull=True),
                name="one_open_case_alert_per_type",
            ),
        ]
        indexes = [
            models.Index(fields=["assigned_to", "status"]),
            models.Index(fields=["alert_type", "status"]),
            models.Index(fields=["case", "status"]),
        ]

    def __str__(self):
        return f"{self.get_alert_type_display()} for {self.case.youth.full_name}"

    @property
    def is_open(self):
        return self.status == AlertStatus.OPEN

    @property
    def age_days(self):
        return (date.today() - self.triggered_date).days

    def resolve(self, status, actor=None, when=None):
        """Close the alert. Used by both the API and the auto-resolution sweep."""
        if status not in {AlertStatus.ACTIONED, AlertStatus.DISMISSED}:
            raise ValidationError({"status": _("An alert is closed as Actioned or Dismissed.")})
        if not self.is_open:
            raise ValidationError(
                {"status": _("This alert is already %(status)s.") % {"status": self.get_status_display()}}
            )

        self.status = status
        self.actioned_date = when or date.today()
        self.actioned_by = actor
        self.save(update_fields=["status", "actioned_date", "actioned_by", "updated_at"])
        return self

    def clean(self):
        errors = {}

        if self.alert_type in AlertType.referral_scoped() and not self.referral_id:
            errors["referral"] = _("%(type)s alerts concern a specific referral.") % {
                "type": self.get_alert_type_display()
            }

        if self.referral_id and self.case_id and self.referral.case_id != self.case_id:
            errors["referral"] = _("The referral belongs to a different case.")

        if errors:
            raise ValidationError(errors)
