"""Serializers for Alert (spec §4.13)."""

from rest_framework import serializers

from .models import Alert, AlertStatus


class AlertSerializer(serializers.ModelSerializer):
    alert_type_display = serializers.CharField(source="get_alert_type_display", read_only=True)
    status_display = serializers.CharField(source="get_status_display", read_only=True)
    assigned_to_name = serializers.CharField(source="assigned_to.full_name", read_only=True)
    actioned_by_name = serializers.CharField(source="actioned_by.full_name", read_only=True, default=None)
    youth_name = serializers.CharField(source="case.youth.full_name", read_only=True)
    woreda = serializers.CharField(source="case.woreda", read_only=True)
    age_days = serializers.IntegerField(read_only=True)

    class Meta:
        model = Alert
        fields = [
            "id",
            "case",
            "youth_name",
            "woreda",
            "referral",
            "alert_type",
            "alert_type_display",
            "summary",
            "triggered_date",
            "threshold_days",
            "age_days",
            "assigned_to",
            "assigned_to_name",
            "status",
            "status_display",
            "actioned_date",
            "actioned_by",
            "actioned_by_name",
        ]
        # Every field is system-set: §4.13 alerts are "generated by system
        # rules", and closing one goes through the action/dismiss endpoints so
        # the actor and date are recorded together.
        read_only_fields = fields


class ResolveAlertSerializer(serializers.Serializer):
    """Close an alert as Actioned or Dismissed (spec §4.13)."""

    status = serializers.ChoiceField(choices=[AlertStatus.ACTIONED, AlertStatus.DISMISSED])
    note = serializers.CharField(
        required=False,
        allow_blank=True,
        help_text="Recorded in the audit history — §9 wants a rationale on status changes.",
    )
