"""Alert API — spec §4.13, §10 Sprint 4."""

from django.core.exceptions import ValidationError as DjangoValidationError
from django.db.models import Count
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema
from rest_framework import filters, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import MethodNotAllowed, ValidationError
from rest_framework.response import Response

from apps.users.permissions import CanAccessCases, IsOperational, ScopedQuerySetMixin

from .models import Alert, AlertStatus, AlertType
from .serializers import AlertSerializer, ResolveAlertSerializer


@extend_schema(tags=["alerts"])
class AlertViewSet(ScopedQuerySetMixin, viewsets.ReadOnlyModelViewSet):
    """Alerts, scoped as case content (§7).

    Read-only apart from the resolution actions: §4.13 alerts are generated by
    system rules, so there is nothing for a client to create or edit.
    """

    queryset = Alert.objects.select_related(
        "case", "case__youth", "case__case_manager", "referral", "assigned_to", "actioned_by"
    )
    serializer_class = AlertSerializer
    permission_classes = [IsOperational, CanAccessCases]

    scope_kind = "case"
    woreda_field = "case__woreda"
    case_manager_field = "case__case_manager_id"

    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    # `case__woreda` backs the shell's woreda scope selector; see ReferralViewSet.
    filterset_fields = ["status", "alert_type", "case", "assigned_to", "case__woreda"]
    search_fields = ["case__youth__full_name", "summary"]
    ordering_fields = ["triggered_date", "alert_type"]
    ordering = ["-triggered_date"]

    def perform_destroy(self, instance):
        raise MethodNotAllowed(
            "DELETE",
            detail="Alerts are actioned or dismissed, never deleted — the resolution is part of the case record.",
        )

    def _resolve(self, request, target_status):
        alert = self.get_object()

        # Read-only roles can see the inbox but must not close items on it (§7).
        if not request.user.can_write_cases():
            raise ValidationError({"detail": "Your role cannot resolve alerts."})

        serializer = ResolveAlertSerializer(data={**request.data, "status": target_status})
        serializer.is_valid(raise_exception=True)

        note = serializer.validated_data.get("note", "")
        if note:
            alert._change_reason = note  # picked up by simple_history

        try:
            alert.resolve(target_status, actor=request.user)
        except DjangoValidationError as exc:
            raise ValidationError(exc.message_dict if hasattr(exc, "message_dict") else exc.messages)

        # Resolving an alert is work on the case.
        alert.case.touch()
        return Response(self.get_serializer(alert).data)

    @extend_schema(request=ResolveAlertSerializer, responses=AlertSerializer)
    # Named `mark_actioned`, not `action`: a method called `action` would shadow
    # the imported @action decorator for every route defined below it in this
    # class body, failing at class-creation time. url_path keeps the REST path
    # as /action/ regardless.
    @action(detail=True, methods=["post"], url_path="action")
    def mark_actioned(self, request, pk=None):
        """Mark the alert Actioned — the underlying situation was dealt with."""
        return self._resolve(request, AlertStatus.ACTIONED)

    @extend_schema(request=ResolveAlertSerializer, responses=AlertSerializer)
    @action(detail=True, methods=["post"])
    def dismiss(self, request, pk=None):
        """Mark the alert Dismissed — no action was needed.

        Kept distinct from Actioned so the §8 reporting can tell "we did
        something" from "this did not warrant anything".
        """
        return self._resolve(request, AlertStatus.DISMISSED)

    @extend_schema(responses=AlertSerializer(many=True))
    @action(detail=False, methods=["get"], url_path="my-inbox")
    def my_inbox(self, request):
        """Open alerts assigned to the requesting user."""
        alerts = self.filter_queryset(self.get_queryset()).open().for_user(request.user)
        page = self.paginate_queryset(alerts)
        serializer = self.get_serializer(page if page is not None else alerts, many=True)
        return self.get_paginated_response(serializer.data) if page is not None else Response(serializer.data)

    @extend_schema(responses={200: None})
    @action(detail=False, methods=["get"])
    def summary(self, request):
        """Open alert counts by type, for the navigation badge and dashboards.

        Respects the caller's scope, so a supervisor's counts cover their
        woredas and a case manager's cover their caseload.
        """
        visible = self.filter_queryset(self.get_queryset())
        by_type = {row["alert_type"]: row["n"] for row in visible.open().values("alert_type").annotate(n=Count("id"))}
        return Response(
            {
                "open_total": visible.open().count(),
                "assigned_to_me": visible.open().for_user(request.user).count(),
                "by_type": [
                    {
                        "alert_type": value,
                        "label": label,
                        "count": by_type.get(value, 0),
                    }
                    for value, label in AlertType.choices
                ],
            }
        )
