"""Alert API — spec §4.13, §10 Sprint 4."""

from django.core.exceptions import ValidationError as DjangoValidationError
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema
from rest_framework import filters, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import MethodNotAllowed, ValidationError
from rest_framework.response import Response

from apps.common.summaries import counters_for, summary_response
from apps.users.permissions import CanAccessCases, IsOperational, ScopedQuerySetMixin

from .models import Alert, AlertStatus, AlertType
from .serializers import AlertSerializer, ResolveAlertSerializer


@extend_schema(tags=["alerts"])
class AlertViewSet(ScopedQuerySetMixin, viewsets.ReadOnlyModelViewSet):
    """Alerts, scoped as case content (§7).

    Read-only apart from the resolution actions: §4.13 alerts are generated by
    system rules, so there is nothing for a client to create or edit.
    """

    queryset = Alert.objects.select_related(
        "case", "case__youth", "case__case_manager", "referral", "assigned_to", "actioned_by"
    )
    serializer_class = AlertSerializer
    permission_classes = [IsOperational, CanAccessCases]

    scope_kind = "case"
    woreda_field = "case__woreda"
    case_manager_field = "case__case_manager_id"

    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    # `case__woreda` backs the shell's woreda scope selector; see ReferralViewSet.
    # `alert_type__in` backs multi-select in the filter chip row.
    filterset_fields = {
        "status": ["exact"],
        "alert_type": ["exact", "in"],
        "case": ["exact"],
        "assigned_to": ["exact"],
        "case__woreda": ["exact"],
    }
    search_fields = ["case__youth__full_name", "summary"]
    ordering_fields = ["triggered_date", "alert_type"]
    ordering = ["-triggered_date"]

    def perform_destroy(self, instance):
        raise MethodNotAllowed(
            "DELETE",
            detail="Alerts are actioned or dismissed, never deleted — the resolution is part of the case record.",
        )

    def _resolve(self, request, target_status):
        alert = self.get_object()

        # Read-only roles can see the inbox but must not close items on it (§7).
        if not request.user.can_write_cases():
            raise ValidationError({"detail": "Your role cannot resolve alerts."})

        serializer = ResolveAlertSerializer(data={**request.data, "status": target_status})
        serializer.is_valid(raise_exception=True)

        note = serializer.validated_data.get("note", "")
        if note:
            alert._change_reason = note  # picked up by simple_history

        try:
            alert.resolve(target_status, actor=request.user)
        except DjangoValidationError as exc:
            raise ValidationError(exc.message_dict if hasattr(exc, "message_dict") else exc.messages)

        # Resolving an alert is work on the case.
        alert.case.touch()
        return Response(self.get_serializer(alert).data)

    @extend_schema(request=ResolveAlertSerializer, responses=AlertSerializer)
    # Named `mark_actioned`, not `action`: a method called `action` would shadow
    # the imported @action decorator for every route defined below it in this
    # class body, failing at class-creation time. url_path keeps the REST path
    # as /action/ regardless.
    @action(detail=True, methods=["post"], url_path="action")
    def mark_actioned(self, request, pk=None):
        """Mark the alert Actioned — the underlying situation was dealt with."""
        return self._resolve(request, AlertStatus.ACTIONED)

    @extend_schema(request=ResolveAlertSerializer, responses=AlertSerializer)
    @action(detail=True, methods=["post"])
    def dismiss(self, request, pk=None):
        """Mark the alert Dismissed — no action was needed.

        Kept distinct from Actioned so the §8 reporting can tell "we did
        something" from "this did not warrant anything".
        """
        return self._resolve(request, AlertStatus.DISMISSED)

    @extend_schema(responses=AlertSerializer(many=True))
    @action(detail=False, methods=["get"], url_path="my-inbox")
    def my_inbox(self, request):
        """Open alerts assigned to the requesting user."""
        alerts = self.filter_queryset(self.get_queryset()).open().for_user(request.user)
        page = self.paginate_queryset(alerts)
        serializer = self.get_serializer(page if page is not None else alerts, many=True)
        return self.get_paginated_response(serializer.data) if page is not None else Response(serializer.data)

    @extend_schema(responses={200: None})
    @action(detail=False, methods=["get"])
    def summary(self, request):
        """Open alert counts by type, for the navigation badge and dashboards.

        Respects the caller's scope, so a supervisor's counts cover their
        woredas and a case manager's cover their caseload.
        """
        visible = self.filter_queryset(self.get_queryset())
        open_alerts = visible.open()

        # Counted through `counters_for`, which groups a fresh subquery on the
        # primary keys rather than this queryset.
        #
        # Grouping it directly was silently wrong: `Meta.ordering` joins the
        # GROUP BY of a `.values().annotate()`, so each alert type came back
        # split across many rows and the dict comprehension kept only the last
        # of them. The screen showed "110 open" beside six counters summing to
        # 51 — the same fault `counters_for` exists to prevent, reproduced by
        # hand here.
        counters = counters_for(open_alerts, param="alert_type__in", field="alert_type", choices=AlertType)
        by_type = [{"alert_type": row["value"], "label": row["label"], "count": row["count"]} for row in counters]
        return Response(
            {
                "open_total": open_alerts.count(),
                "assigned_to_me": open_alerts.for_user(request.user).count(),
                # Kept for the navigation badge and the dashboards.
                "by_type": by_type,
                **summary_response(open_alerts, counters),
            }
        )
