# Generated by Django 5.2.17 on 2026-08-11 11:37

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_historicalprofilingrecord_pathwayassignment_and_more"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureReasonCode",
            fields=[
                ("code", models.SlugField(max_length=64, primary_key=True, serialize=False, verbose_name="code")),
                ("label", models.CharField(max_length=128, verbose_name="label")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to retire a term. Existing referrals keep it.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="sort order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requires_note", models.BooleanField(default=False, verbose_name="requires a note")),
            ],
            options={
                "verbose_name": "failure reason code",
                "verbose_name_plural": "failure reason codes",
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutcomeType",
            fields=[
                ("code", models.SlugField(max_length=64, primary_key=True, serialize=False, verbose_name="code")),
                ("label", models.CharField(max_length=128, verbose_name="label")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to retire a term. Existing referrals keep it.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="sort order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requires_note", models.BooleanField(default=False, verbose_name="requires a note")),
            ],
            options={
                "verbose_name": "outcome type",
                "verbose_name_plural": "outcome types",
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralCategory",
            fields=[
                ("code", models.SlugField(max_length=64, primary_key=True, serialize=False, verbose_name="code")),
                ("label", models.CharField(max_length=128, verbose_name="label")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to retire a term. Existing referrals keep it.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="sort order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exempt_from_parallel_cap",
                    models.BooleanField(
                        default=False,
                        help_text="Referrals in this category run alongside the two-referral cap rather than counting toward it (spec §6.3 — working default, pending Phase 1 sign-off).",
                        verbose_name="exempt from the parallel cap",
                    ),
                ),
                (
                    "requires_note",
                    models.BooleanField(
                        default=False,
                        help_text="Catch-all categories such as Other require a free-text note (spec §5.1).",
                        verbose_name="requires a note",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral category",
                "verbose_name_plural": "referral categories",
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalFailureReasonCode",
            fields=[
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                ("label", models.CharField(max_length=128, verbose_name="label")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to retire a term. Existing referrals keep it.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="sort order")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("requires_note", models.BooleanField(default=False, verbose_name="requires a note")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical failure reason code",
                "verbose_name_plural": "historical failure reason codes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOutcomeType",
            fields=[
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                ("label", models.CharField(max_length=128, verbose_name="label")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to retire a term. Existing referrals keep it.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="sort order")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("requires_note", models.BooleanField(default=False, verbose_name="requires a note")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical outcome type",
                "verbose_name_plural": "historical outcome types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReferralCategory",
            fields=[
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                ("label", models.CharField(max_length=128, verbose_name="label")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to retire a term. Existing referrals keep it.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="sort order")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "exempt_from_parallel_cap",
                    models.BooleanField(
                        default=False,
                        help_text="Referrals in this category run alongside the two-referral cap rather than counting toward it (spec §6.3 — working default, pending Phase 1 sign-off).",
                        verbose_name="exempt from the parallel cap",
                    ),
                ),
                (
                    "requires_note",
                    models.BooleanField(
                        default=False,
                        help_text="Catch-all categories such as Other require a free-text note (spec §5.1).",
                        verbose_name="requires a note",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical referral category",
                "verbose_name_plural": "historical referral categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "referral_trigger",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("ONWARD", "Onward"), ("REPLACEMENT", "Replacement")],
                        db_index=True,
                        default="MANUAL",
                        max_length=16,
                        verbose_name="referral trigger",
                    ),
                ),
                ("is_parallel", models.BooleanField(default=False, verbose_name="is parallel")),
                (
                    "parallel_group_id",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="parallel group"),
                ),
                (
                    "receiving_contact_name",
                    models.CharField(blank=True, max_length=255, verbose_name="receiving contact"),
                ),
                (
                    "initiated_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="initiated date"),
                ),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("DECLINED", "Declined"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="confirmation status",
                    ),
                ),
                ("confirmed_date", models.DateField(blank=True, null=True, verbose_name="confirmed date")),
                ("confirmed_by", models.CharField(blank=True, max_length=255, verbose_name="confirmed by")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REPLACED", "Replaced"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING_CONFIRMATION",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                ("outcome_date", models.DateField(blank=True, null=True, verbose_name="outcome date")),
                (
                    "outcome_verification_method",
                    models.CharField(blank=True, max_length=255, verbose_name="verification method"),
                ),
                ("failure_date", models.DateField(blank=True, null=True, verbose_name="failure date")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "failure_reason_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="referrals.failurereasoncode",
                        verbose_name="failure reason",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="initiated by",
                    ),
                ),
                (
                    "outcome_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="referrals.outcometype",
                        verbose_name="outcome type",
                    ),
                ),
                (
                    "outcome_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_referral_outcomes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="outcome verified by",
                    ),
                ),
                (
                    "parent_referral",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for Onward and Replacement referrals; links to the referral that preceded it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="referrals.referral",
                        verbose_name="parent referral",
                    ),
                ),
                (
                    "receiving_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_referrals",
                        to="partners.partner",
                        verbose_name="receiving partner",
                    ),
                ),
                (
                    "replacement_referral",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set once this referral has been replaced; forward link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="referrals.referral",
                        verbose_name="replacement referral",
                    ),
                ),
                (
                    "referral_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="referrals.referralcategory",
                        verbose_name="referral category",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral",
                "verbose_name_plural": "referrals",
                "ordering": ["-initiated_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="outcometype",
            name="applies_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to allow this outcome for any category.",
                related_name="outcome_types",
                to="referrals.referralcategory",
                verbose_name="applies to categories",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReferral",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                (
                    "referral_trigger",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("ONWARD", "Onward"), ("REPLACEMENT", "Replacement")],
                        db_index=True,
                        default="MANUAL",
                        max_length=16,
                        verbose_name="referral trigger",
                    ),
                ),
                ("is_parallel", models.BooleanField(default=False, verbose_name="is parallel")),
                (
                    "parallel_group_id",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="parallel group"),
                ),
                (
                    "receiving_contact_name",
                    models.CharField(blank=True, max_length=255, verbose_name="receiving contact"),
                ),
                (
                    "initiated_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="initiated date"),
                ),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("DECLINED", "Declined"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="confirmation status",
                    ),
                ),
                ("confirmed_date", models.DateField(blank=True, null=True, verbose_name="confirmed date")),
                ("confirmed_by", models.CharField(blank=True, max_length=255, verbose_name="confirmed by")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REPLACED", "Replaced"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING_CONFIRMATION",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                ("outcome_date", models.DateField(blank=True, null=True, verbose_name="outcome date")),
                (
                    "outcome_verification_method",
                    models.CharField(blank=True, max_length=255, verbose_name="verification method"),
                ),
                ("failure_date", models.DateField(blank=True, null=True, verbose_name="failure date")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "failure_reason_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.failurereasoncode",
                        verbose_name="failure reason",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="initiated by",
                    ),
                ),
                (
                    "outcome_verified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="outcome verified by",
                    ),
                ),
                (
                    "receiving_partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="partners.partner",
                        verbose_name="receiving partner",
                    ),
                ),
                (
                    "outcome_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.outcometype",
                        verbose_name="outcome type",
                    ),
                ),
                (
                    "parent_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set for Onward and Replacement referrals; links to the referral that preceded it.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="parent referral",
                    ),
                ),
                (
                    "replacement_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set once this referral has been replaced; forward link.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="replacement referral",
                    ),
                ),
                (
                    "referral_category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referralcategory",
                        verbose_name="referral category",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical referral",
                "verbose_name_plural": "historical referrals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["case", "-initiated_date"], name="referrals_r_case_id_4456e9_idx"),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["status", "referral_category"], name="referrals_r_status_ba4e57_idx"),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["receiving_partner", "status"], name="referrals_r_receivi_bf241f_idx"),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["parallel_group_id"], name="referrals_r_paralle_319837_idx"),
        ),
    ]
