# Generated by Django 5.2.17 on 2026-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloutcometype",
            name="counts_as_placement",
            field=models.BooleanField(
                default=False,
                help_text="Include referrals closed with this outcome in the programme dashboard's placement figures.",
                verbose_name="counts as a placement",
            ),
        ),
        migrations.AddField(
            model_name="outcometype",
            name="counts_as_placement",
            field=models.BooleanField(
                default=False,
                help_text="Include referrals closed with this outcome in the programme dashboard's placement figures.",
                verbose_name="counts as a placement",
            ),
        ),
    ]
