# Generated by Django 5.2.17 on 2026-08-18 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_historicaloutcometype_counts_as_placement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreferral",
            name="confirmation_recorded_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Set when a staff member recorded the partner's answer rather than the partner entering it.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="confirmation recorded by",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="confirmation_recorded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when a staff member recorded the partner's answer rather than the partner entering it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_confirmations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="confirmation recorded by",
            ),
        ),
    ]
