# Generated by Django 5.2.17 on 2026-08-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0003_historicalreferral_confirmation_recorded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreferral",
            name="service_start_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="The date the youth presented to the receiving partner.",
                null=True,
                verbose_name="service start date",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferral",
            name="verification_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF_REPORTED", "Self-reported by the youth"),
                    ("PROVIDER_CONFIRMED", "Confirmed by the receiving provider"),
                    ("EMPLOYER_CONFIRMED", "Confirmed by the employer"),
                    ("DOCUMENT_VERIFIED", "Verified against a document"),
                ],
                db_index=True,
                help_text="Who verified the outcome. Anything but self-reported counts as externally verified.",
                max_length=24,
                verbose_name="verification source",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="service_start_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="The date the youth presented to the receiving partner.",
                null=True,
                verbose_name="service start date",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="verification_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF_REPORTED", "Self-reported by the youth"),
                    ("PROVIDER_CONFIRMED", "Confirmed by the receiving provider"),
                    ("EMPLOYER_CONFIRMED", "Confirmed by the employer"),
                    ("DOCUMENT_VERIFIED", "Verified against a document"),
                ],
                db_index=True,
                help_text="Who verified the outcome. Anything but self-reported counts as externally verified.",
                max_length=24,
                verbose_name="verification source",
            ),
        ),
    ]
