# Generated by Django 5.2.17 on 2026-08-18 04:12

from django.conf import settings
from django.db import migrations, models


def clear_orphaned_confirmed_dates(apps, schema_editor):
    """Drop confirmation dates left on referrals that were never confirmed.

    Written by a refused transition whose in-memory field updates survived the
    database rollback and were persisted by the next transition on the same
    object — see `Referral.transition_to`. The date is the orphan: the
    confirmation genuinely never happened, the referral went on to be cancelled,
    and no partner ever answered.

    The inverse case — CONFIRMED with no date — is not touched, because that
    would mean inventing a date for a confirmation that did occur. There are
    none, and if any appear they need a person.
    """
    Referral = apps.get_model("referrals", "Referral")
    cleared = Referral.objects.filter(confirmation_status="PENDING", confirmed_date__isnull=False).update(
        confirmed_date=None
    )
    print(f"\n  cleared {cleared} orphaned confirmed_date value(s).")


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_historicalprofilingrecord_pathwayassignment_and_more"),
        ("partners", "0001_initial"),
        ("referrals", "0005_backfill_verification_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_orphaned_confirmed_dates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confirmation_status", "PENDING"), ("confirmed_date__isnull", False), _negated=True
                ),
                name="referral_no_confirmed_date_while_pending",
            ),
        ),
    ]
