# Generated by Django 5.2.17 on 2026-08-20 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_caseaction_index_names"),
        ("partners", "0002_historicalpartner_standing_partner_standing_and_more"),
        ("referrals", "0006_confirmed_date_requires_confirmation"),
        ("users", "0006_historicaluser_wlt_scope_location_and_more"),
        ("wlt", "0001_initial"),
        ("youth", "0002_historicalyouth_settlement_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreferral",
            name="subject_cla",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wlt.cla",
                verbose_name="CLA subject",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferral",
            name="subject_federation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wlt.federation",
                verbose_name="federation subject",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferral",
            name="subject_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wlt.group",
                verbose_name="SHG subject",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferral",
            name="subject_youth",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="A person referred outside a youth-employment case — a WLT member, for instance.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="youth.youth",
                verbose_name="youth subject",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="subject_cla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="wlt.cla",
                verbose_name="CLA subject",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="subject_federation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="wlt.federation",
                verbose_name="federation subject",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="subject_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="wlt.group",
                verbose_name="SHG subject",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="subject_youth",
            field=models.ForeignKey(
                blank=True,
                help_text="A person referred outside a youth-employment case — a WLT member, for instance.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_referrals",
                to="youth.youth",
                verbose_name="youth subject",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferralcategory",
            name="allowed_subject_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Subjects a referral in this category may name: CASE, YOUTH, GROUP, CLA or FEDERATION.",
                verbose_name="allowed subject types",
            ),
        ),
        migrations.AddField(
            model_name="referralcategory",
            name="allowed_subject_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Subjects a referral in this category may name: CASE, YOUTH, GROUP, CLA or FEDERATION.",
                verbose_name="allowed subject types",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="cases.case",
                verbose_name="case",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                condition=models.Q(("subject_group__isnull", False)),
                fields=["subject_group"],
                name="referral_subject_group_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                condition=models.Q(("subject_cla__isnull", False)),
                fields=["subject_cla"],
                name="referral_subject_cla_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                condition=models.Q(("subject_federation__isnull", False)),
                fields=["subject_federation"],
                name="referral_subject_fed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                condition=models.Q(("subject_youth__isnull", False)),
                fields=["subject_youth"],
                name="referral_subject_youth_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("case__isnull", False),
                        ("subject_youth__isnull", True),
                        ("subject_group__isnull", True),
                        ("subject_cla__isnull", True),
                        ("subject_federation__isnull", True),
                    ),
                    models.Q(
                        ("case__isnull", True),
                        ("subject_youth__isnull", False),
                        ("subject_group__isnull", True),
                        ("subject_cla__isnull", True),
                        ("subject_federation__isnull", True),
                    ),
                    models.Q(
                        ("case__isnull", True),
                        ("subject_youth__isnull", True),
                        ("subject_group__isnull", False),
                        ("subject_cla__isnull", True),
                        ("subject_federation__isnull", True),
                    ),
                    models.Q(
                        ("case__isnull", True),
                        ("subject_youth__isnull", True),
                        ("subject_group__isnull", True),
                        ("subject_cla__isnull", False),
                        ("subject_federation__isnull", True),
                    ),
                    models.Q(
                        ("case__isnull", True),
                        ("subject_youth__isnull", True),
                        ("subject_group__isnull", True),
                        ("subject_cla__isnull", True),
                        ("subject_federation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="referral_exactly_one_subject",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferral",
            name="subject_type",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(case__isnull=False, then=models.Value("CASE")),
                    models.When(subject_youth__isnull=False, then=models.Value("YOUTH")),
                    models.When(subject_group__isnull=False, then=models.Value("GROUP")),
                    models.When(subject_cla__isnull=False, then=models.Value("CLA")),
                    models.When(subject_federation__isnull=False, then=models.Value("FEDERATION")),
                    output_field=models.CharField(max_length=16),
                ),
                output_field=models.CharField(max_length=16),
                verbose_name="subject type",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="subject_type",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(case__isnull=False, then=models.Value("CASE")),
                    models.When(subject_youth__isnull=False, then=models.Value("YOUTH")),
                    models.When(subject_group__isnull=False, then=models.Value("GROUP")),
                    models.When(subject_cla__isnull=False, then=models.Value("CLA")),
                    models.When(subject_federation__isnull=False, then=models.Value("FEDERATION")),
                    output_field=models.CharField(max_length=16),
                ),
                output_field=models.CharField(max_length=16),
                verbose_name="subject type",
            ),
        ),
    ]
