# Generated by Django 5.2.17 on 2026-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0008_backfill_allowed_subject_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreferralcategory",
            name="creates_training_enrolment",
            field=models.BooleanField(
                default=False,
                help_text="A referral in this category may open a §4.5 training enrolment. Seeded true for Training; set it on any other category that delivers a course.",
                verbose_name="creates a training enrolment",
            ),
        ),
        migrations.AddField(
            model_name="referralcategory",
            name="creates_training_enrolment",
            field=models.BooleanField(
                default=False,
                help_text="A referral in this category may open a §4.5 training enrolment. Seeded true for Training; set it on any other category that delivers a course.",
                verbose_name="creates a training enrolment",
            ),
        ),
    ]
