# Generated by Django 5.2.17 on 2026-08-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0010_seed_creates_training_enrolment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreferralcategory",
            name="creates_enterprise",
            field=models.BooleanField(
                default=False,
                help_text="A referral in this category may open a §4.8 enterprise record. Seeded true for Enterprise and Finance Access.",
                verbose_name="creates an enterprise record",
            ),
        ),
        migrations.AddField(
            model_name="historicalreferralcategory",
            name="creates_placement",
            field=models.BooleanField(
                default=False,
                help_text="A referral in this category may open a §4.7 placement. Seeded true for Employment and Apprenticeship.",
                verbose_name="creates a placement",
            ),
        ),
        migrations.AddField(
            model_name="referralcategory",
            name="creates_enterprise",
            field=models.BooleanField(
                default=False,
                help_text="A referral in this category may open a §4.8 enterprise record. Seeded true for Enterprise and Finance Access.",
                verbose_name="creates an enterprise record",
            ),
        ),
        migrations.AddField(
            model_name="referralcategory",
            name="creates_placement",
            field=models.BooleanField(
                default=False,
                help_text="A referral in this category may open a §4.7 placement. Seeded true for Employment and Apprenticeship.",
                verbose_name="creates a placement",
            ),
        ),
    ]
