# Generated by Django 5.2.17 on 2026-08-20 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("wlt", "0002_ledger_invariants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="group",
            name="wlt_phase_only_when_operating",
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_phase", ""),
                    ("status__in", ("ACTIVE", "AT_RISK", "DORMANT", "SPLIT", "MERGED", "DISSOLVED")),
                    _connector="OR",
                ),
                name="wlt_phase_only_when_operating",
            ),
        ),
    ]
