# Generated by Django 5.2.17 on 2026-08-22 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wlt", "0004_reporting_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicelinkage",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The earlier linkage that led to this one. Multiple onward linkages may run simultaneously.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wlt.servicelinkage",
                verbose_name="onward from",
            ),
        ),
        migrations.AddField(
            model_name="servicelinkage",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                help_text="The earlier linkage that led to this one. Multiple onward linkages may run simultaneously.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="onward_linkages",
                to="wlt.servicelinkage",
                verbose_name="onward from",
            ),
        ),
    ]
