# Generated by Django 5.2.17 on 2026-08-20 06:19

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_caseaction_index_names"),
        ("referrals", "0008_backfill_allowed_subject_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPlacement",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("employer_name", models.CharField(db_index=True, max_length=255, verbose_name="employer")),
                ("sector", models.CharField(max_length=128, verbose_name="sector")),
                (
                    "placement_type",
                    models.CharField(
                        choices=[("JOB", "Job"), ("APPRENTICESHIP", "Apprenticeship")],
                        max_length=16,
                        verbose_name="placement type",
                    ),
                ),
                ("placement_date", models.DateField(db_index=True, verbose_name="placement date")),
                (
                    "wage_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty where the youth would not say. A guessed wage is worse than a blank.",
                        max_digits=12,
                        null=True,
                        verbose_name="wage (ETB per month)",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No written contract"),
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed term"),
                            ("CASUAL", "Casual or daily"),
                            ("APPRENTICESHIP", "Apprenticeship agreement"),
                        ],
                        default="NONE",
                        max_length=24,
                        verbose_name="contract type",
                    ),
                ),
                ("contract_duration", models.CharField(blank=True, max_length=128, verbose_name="contract duration")),
                (
                    "is_subsidised",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="A subsidised placement is excluded from the reported retention figure.",
                        verbose_name="wage subsidised by the programme",
                    ),
                ),
                ("exit_date", models.DateField(blank=True, db_index=True, null=True, verbose_name="exit date")),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_JOB", "Left for a better job"),
                            ("RESIGNED", "Resigned"),
                            ("CONTRACT_ENDED", "Contract ended"),
                            ("REDUNDANT", "Made redundant"),
                            ("DISMISSED", "Dismissed"),
                            ("HEALTH", "Health or family reasons"),
                            ("MIGRATED", "Migrated"),
                            ("LOST_TO_FOLLOW_UP", "Lost to follow-up"),
                        ],
                        max_length=24,
                        verbose_name="exit reason",
                    ),
                ),
                ("exit_note", models.TextField(blank=True, verbose_name="exit note")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The employer liaison or case manager who entered this record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "source_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set when the placement resulted from a referral. Empty when the youth found the work herself.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="source referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical placement",
                "verbose_name_plural": "historical placements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("employer_name", models.CharField(db_index=True, max_length=255, verbose_name="employer")),
                ("sector", models.CharField(max_length=128, verbose_name="sector")),
                (
                    "placement_type",
                    models.CharField(
                        choices=[("JOB", "Job"), ("APPRENTICESHIP", "Apprenticeship")],
                        max_length=16,
                        verbose_name="placement type",
                    ),
                ),
                ("placement_date", models.DateField(db_index=True, verbose_name="placement date")),
                (
                    "wage_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty where the youth would not say. A guessed wage is worse than a blank.",
                        max_digits=12,
                        null=True,
                        verbose_name="wage (ETB per month)",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No written contract"),
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed term"),
                            ("CASUAL", "Casual or daily"),
                            ("APPRENTICESHIP", "Apprenticeship agreement"),
                        ],
                        default="NONE",
                        max_length=24,
                        verbose_name="contract type",
                    ),
                ),
                ("contract_duration", models.CharField(blank=True, max_length=128, verbose_name="contract duration")),
                (
                    "is_subsidised",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="A subsidised placement is excluded from the reported retention figure.",
                        verbose_name="wage subsidised by the programme",
                    ),
                ),
                ("exit_date", models.DateField(blank=True, db_index=True, null=True, verbose_name="exit date")),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BETTER_JOB", "Left for a better job"),
                            ("RESIGNED", "Resigned"),
                            ("CONTRACT_ENDED", "Contract ended"),
                            ("REDUNDANT", "Made redundant"),
                            ("DISMISSED", "Dismissed"),
                            ("HEALTH", "Health or family reasons"),
                            ("MIGRATED", "Migrated"),
                            ("LOST_TO_FOLLOW_UP", "Lost to follow-up"),
                        ],
                        max_length=24,
                        verbose_name="exit reason",
                    ),
                ),
                ("exit_note", models.TextField(blank=True, verbose_name="exit note")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="The employer liaison or case manager who entered this record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_placements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "source_referral",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the placement resulted from a referral. Empty when the youth found the work herself.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placements",
                        to="referrals.referral",
                        verbose_name="source referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "placement",
                "verbose_name_plural": "placements",
                "ordering": ["-placement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRetentionCheck",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                (
                    "checkpoint",
                    models.PositiveSmallIntegerField(
                        choices=[(30, "30 days"), (60, "60 days"), (90, "90 days")], verbose_name="checkpoint (days)"
                    ),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="due")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not checked yet"),
                            ("RETAINED", "Still in the placement"),
                            ("EXITED", "No longer in the placement"),
                            ("UNREACHABLE", "Could not be contacted"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("checked_on", models.DateField(blank=True, null=True, verbose_name="checked on")),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="checked by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="placements.placement",
                        verbose_name="placement",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical retention check",
                "verbose_name_plural": "historical retention checks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RetentionCheck",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "checkpoint",
                    models.PositiveSmallIntegerField(
                        choices=[(30, "30 days"), (60, "60 days"), (90, "90 days")], verbose_name="checkpoint (days)"
                    ),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="due")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not checked yet"),
                            ("RETAINED", "Still in the placement"),
                            ("EXITED", "No longer in the placement"),
                            ("UNREACHABLE", "Could not be contacted"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("checked_on", models.DateField(blank=True, null=True, verbose_name="checked on")),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="checked by",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_checks",
                        to="placements.placement",
                        verbose_name="placement",
                    ),
                ),
            ],
            options={
                "verbose_name": "retention check",
                "verbose_name_plural": "retention checks",
                "ordering": ["placement", "checkpoint"],
            },
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["case", "-placement_date"], name="placements__case_id_3ee308_idx"),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["placement_date", "is_subsidised"], name="placements__placeme_3f7983_idx"),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exit_date__isnull", True), ("exit_date__gte", models.F("placement_date")), _connector="OR"
                ),
                name="placement_exit_after_placement",
            ),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exit_date__isnull", True), models.Q(("exit_reason", ""), _negated=True), _connector="OR"
                ),
                name="placement_exit_needs_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(("wage_amount__isnull", True), ("wage_amount__gte", 0), _connector="OR"),
                name="placement_wage_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="retentioncheck",
            index=models.Index(fields=["status", "due_date"], name="placements__status_70a209_idx"),
        ),
        migrations.AddConstraint(
            model_name="retentioncheck",
            constraint=models.UniqueConstraint(fields=("placement", "checkpoint"), name="retention_one_per_checkpoint"),
        ),
        migrations.AddConstraint(
            model_name="retentioncheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "PENDING"),
                    models.Q(("checked_by__isnull", False), ("checked_on__isnull", False)),
                    _connector="OR",
                ),
                name="retention_answer_needs_actor",
            ),
        ),
    ]
