# Generated by Django 5.2.17 on 2026-08-13 11:55

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_historicalprofilingrecord_pathwayassignment_and_more"),
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAlert",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("STALL", "Stall Alert"),
                            ("REFERRAL_CONFIRMATION_OVERDUE", "Referral Confirmation Overdue"),
                            ("FOLLOW_UP_DUE", "Follow-Up Due"),
                            ("ONWARD_REFERRAL_PROMPT", "Onward Referral Prompt"),
                            ("REPLACEMENT_REFERRAL_PROMPT", "Replacement Referral Prompt"),
                            ("RETENTION_CHECK_DUE", "Retention Check Due"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "triggered_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="triggered date"),
                ),
                (
                    "threshold_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The threshold in force when this alert was raised. Configurable per alert type.",
                        verbose_name="threshold days",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("ACTIONED", "Actioned"), ("DISMISSED", "Dismissed")],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("actioned_date", models.DateField(blank=True, null=True, verbose_name="actioned date")),
                ("summary", models.CharField(blank=True, max_length=255, verbose_name="summary")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actioned by",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical alert",
                "verbose_name_plural": "historical alerts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("STALL", "Stall Alert"),
                            ("REFERRAL_CONFIRMATION_OVERDUE", "Referral Confirmation Overdue"),
                            ("FOLLOW_UP_DUE", "Follow-Up Due"),
                            ("ONWARD_REFERRAL_PROMPT", "Onward Referral Prompt"),
                            ("REPLACEMENT_REFERRAL_PROMPT", "Replacement Referral Prompt"),
                            ("RETENTION_CHECK_DUE", "Retention Check Due"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "triggered_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="triggered date"),
                ),
                (
                    "threshold_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The threshold in force when this alert was raised. Configurable per alert type.",
                        verbose_name="threshold days",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("ACTIONED", "Actioned"), ("DISMISSED", "Dismissed")],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("actioned_date", models.DateField(blank=True, null=True, verbose_name="actioned date")),
                ("summary", models.CharField(blank=True, max_length=255, verbose_name="summary")),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actioned_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actioned by",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="referrals.referral",
                        verbose_name="referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "alert",
                "verbose_name_plural": "alerts",
                "ordering": ["-triggered_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["assigned_to", "status"], name="alerts_aler_assigne_28b530_idx"),
                    models.Index(fields=["alert_type", "status"], name="alerts_aler_alert_t_82e8cd_idx"),
                    models.Index(fields=["case", "status"], name="alerts_aler_case_id_2952ea_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OPEN")),
                        fields=("case", "alert_type", "referral"),
                        name="one_open_alert_per_case_type_referral",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("referral__isnull", True), ("status", "OPEN")),
                        fields=("case", "alert_type"),
                        name="one_open_case_alert_per_type",
                    ),
                ],
            },
        ),
    ]
