# Generated by Django 5.2.17 on 2026-08-10 16:57

import apps.users.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True, verbose_name="username")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("full_name", models.CharField(max_length=255, verbose_name="full name")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OUTREACH_WORKER", "Outreach worker / community facilitator"),
                            ("CASE_MANAGER", "Youth case manager"),
                            ("TRAINER", "Trainer / training officer"),
                            ("EMPLOYER_LIAISON", "Employer liaison staff"),
                            ("ENTERPRISE_OFFICER", "Enterprise development officer"),
                            ("PARTNER_STAFF", "Referral partner staff"),
                            ("SUPERVISOR", "Woreda / programme supervisor"),
                            ("PROGRAMME_MANAGER", "Programme manager"),
                            ("MNE_STAFF", "M&E staff"),
                            ("SYSTEM_ADMIN", "System administrator"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="role",
                    ),
                ),
                (
                    "woreda_assignment",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        help_text="Woredas this user may work in. Ignored for roles scoped to all records.",
                        size=None,
                        verbose_name="woreda assignment",
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, help_text="Django admin access.")),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["full_name"],
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("username", models.CharField(db_index=True, max_length=150, verbose_name="username")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("full_name", models.CharField(max_length=255, verbose_name="full name")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OUTREACH_WORKER", "Outreach worker / community facilitator"),
                            ("CASE_MANAGER", "Youth case manager"),
                            ("TRAINER", "Trainer / training officer"),
                            ("EMPLOYER_LIAISON", "Employer liaison staff"),
                            ("ENTERPRISE_OFFICER", "Enterprise development officer"),
                            ("PARTNER_STAFF", "Referral partner staff"),
                            ("SUPERVISOR", "Woreda / programme supervisor"),
                            ("PROGRAMME_MANAGER", "Programme manager"),
                            ("MNE_STAFF", "M&E staff"),
                            ("SYSTEM_ADMIN", "System administrator"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="role",
                    ),
                ),
                (
                    "woreda_assignment",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        help_text="Woredas this user may work in. Ignored for roles scoped to all records.",
                        size=None,
                        verbose_name="woreda assignment",
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, help_text="Django admin access.")),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role", "account_status"], name="users_user_role_1f6047_idx"),
        ),
    ]
