# Generated by Django 5.2.17 on 2026-08-11 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Required for referral partner staff; scopes them to their own institution's referrals.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="partners.partner",
                verbose_name="partner organisation",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for referral partner staff; scopes them to their own institution's referrals.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="partners.partner",
                verbose_name="partner organisation",
            ),
        ),
    ]
