# Generated by Django 5.2.17 on 2026-08-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_email_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
