# Generated by Django 5.2.17 on 2026-08-20 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0005_password_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="wlt_scope_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Region, woreda or kebele this WLT account works in. Groups below it are visible.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.location",
                verbose_name="WLT scope",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wlt_scope_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Region, woreda or kebele this WLT account works in. Groups below it are visible.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scoped_users",
                to="locations.location",
                verbose_name="WLT scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OUTREACH_WORKER", "Outreach worker / community facilitator"),
                    ("CASE_MANAGER", "Youth case manager"),
                    ("TRAINER", "Trainer / training officer"),
                    ("EMPLOYER_LIAISON", "Employer liaison staff"),
                    ("ENTERPRISE_OFFICER", "Enterprise development officer"),
                    ("PARTNER_STAFF", "Referral partner staff"),
                    ("SUPERVISOR", "Woreda / programme supervisor"),
                    ("PROGRAMME_MANAGER", "Programme manager"),
                    ("MNE_STAFF", "M&E staff"),
                    ("SYSTEM_ADMIN", "System administrator"),
                    ("WLT_FACILITATOR", "WLT group facilitator"),
                    ("WLT_WOREDA_OFFICER", "WLT woreda officer (FSCO)"),
                    ("WLT_REGION_OFFICER", "WLT region officer (FSCO)"),
                    ("WLT_FEDERAL_OFFICER", "WLT federal officer (FSCO)"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("OUTREACH_WORKER", "Outreach worker / community facilitator"),
                    ("CASE_MANAGER", "Youth case manager"),
                    ("TRAINER", "Trainer / training officer"),
                    ("EMPLOYER_LIAISON", "Employer liaison staff"),
                    ("ENTERPRISE_OFFICER", "Enterprise development officer"),
                    ("PARTNER_STAFF", "Referral partner staff"),
                    ("SUPERVISOR", "Woreda / programme supervisor"),
                    ("PROGRAMME_MANAGER", "Programme manager"),
                    ("MNE_STAFF", "M&E staff"),
                    ("SYSTEM_ADMIN", "System administrator"),
                    ("WLT_FACILITATOR", "WLT group facilitator"),
                    ("WLT_WOREDA_OFFICER", "WLT woreda officer (FSCO)"),
                    ("WLT_REGION_OFFICER", "WLT region officer (FSCO)"),
                    ("WLT_FEDERAL_OFFICER", "WLT federal officer (FSCO)"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="role",
            ),
        ),
    ]
