# Generated by Django 5.2.17 on 2026-08-20 07:37

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_caseaction_index_names"),
        ("referrals", "0008_backfill_allowed_subject_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("business_name", models.CharField(blank=True, max_length=255, verbose_name="business name")),
                ("sector", models.CharField(blank=True, max_length=128, verbose_name="sector")),
                (
                    "business_plan_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("DRAFTED", "Drafted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("REVISION_REQUESTED", "Revision requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=24,
                        verbose_name="business plan status",
                    ),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("GRANT", "Grant"),
                            ("LOAN", "Loan"),
                            ("IN_KIND", "In-kind (equipment or stock)"),
                        ],
                        default="NONE",
                        max_length=16,
                        verbose_name="support type",
                    ),
                ),
                (
                    "grant_or_loan_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="grant or loan amount (ETB)",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="disbursement date"),
                ),
                (
                    "mentorship_sessions_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="mentorship sessions"),
                ),
                (
                    "business_registration_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not required at this scale"),
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("REGISTERED", "Registered"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                        verbose_name="registration status",
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=64, verbose_name="registration number"),
                ),
                (
                    "market_linkage_status",
                    models.CharField(
                        choices=[
                            ("NONE", "No market linkage"),
                            ("IDENTIFIED", "Buyer identified"),
                            ("NEGOTIATING", "Negotiating"),
                            ("TRADING", "Trading"),
                            ("LAPSED", "Lapsed"),
                        ],
                        default="NONE",
                        max_length=16,
                        verbose_name="market linkage",
                    ),
                ),
                (
                    "started_trading_on",
                    models.DateField(
                        blank=True,
                        help_text="The date the business first sold something. Not the disbursement date.",
                        null=True,
                        verbose_name="started trading on",
                    ),
                ),
                ("closed_on", models.DateField(blank=True, null=True, verbose_name="closed on")),
                ("closure_reason", models.TextField(blank=True, verbose_name="closure reason")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprises",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="The enterprise officer who owns this record. Scopes her own caseload.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_enterprises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "source_referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprises",
                        to="referrals.referral",
                        verbose_name="source referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "enterprise",
                "verbose_name_plural": "enterprises",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseMilestone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("milestone_name", models.CharField(max_length=255, verbose_name="milestone")),
                ("target_date", models.DateField(db_index=True, verbose_name="target date")),
                ("completion_date", models.DateField(blank=True, null=True, verbose_name="completion date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACHIEVED", "Achieved"),
                            ("MISSED", "Missed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="enterprises.enterprise",
                        verbose_name="enterprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "enterprise milestone",
                "verbose_name_plural": "enterprise milestones",
                "ordering": ["enterprise", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEnterprise",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("business_name", models.CharField(blank=True, max_length=255, verbose_name="business name")),
                ("sector", models.CharField(blank=True, max_length=128, verbose_name="sector")),
                (
                    "business_plan_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("DRAFTED", "Drafted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("REVISION_REQUESTED", "Revision requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=24,
                        verbose_name="business plan status",
                    ),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("GRANT", "Grant"),
                            ("LOAN", "Loan"),
                            ("IN_KIND", "In-kind (equipment or stock)"),
                        ],
                        default="NONE",
                        max_length=16,
                        verbose_name="support type",
                    ),
                ),
                (
                    "grant_or_loan_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="grant or loan amount (ETB)",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="disbursement date"),
                ),
                (
                    "mentorship_sessions_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="mentorship sessions"),
                ),
                (
                    "business_registration_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not required at this scale"),
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("REGISTERED", "Registered"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                        verbose_name="registration status",
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=64, verbose_name="registration number"),
                ),
                (
                    "market_linkage_status",
                    models.CharField(
                        choices=[
                            ("NONE", "No market linkage"),
                            ("IDENTIFIED", "Buyer identified"),
                            ("NEGOTIATING", "Negotiating"),
                            ("TRADING", "Trading"),
                            ("LAPSED", "Lapsed"),
                        ],
                        default="NONE",
                        max_length=16,
                        verbose_name="market linkage",
                    ),
                ),
                (
                    "started_trading_on",
                    models.DateField(
                        blank=True,
                        help_text="The date the business first sold something. Not the disbursement date.",
                        null=True,
                        verbose_name="started trading on",
                    ),
                ),
                ("closed_on", models.DateField(blank=True, null=True, verbose_name="closed on")),
                ("closure_reason", models.TextField(blank=True, verbose_name="closure reason")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The enterprise officer who owns this record. Scopes her own caseload.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "source_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="source referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical enterprise",
                "verbose_name_plural": "historical enterprises",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEnterpriseMilestone",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("milestone_name", models.CharField(max_length=255, verbose_name="milestone")),
                ("target_date", models.DateField(db_index=True, verbose_name="target date")),
                ("completion_date", models.DateField(blank=True, null=True, verbose_name="completion date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACHIEVED", "Achieved"),
                            ("MISSED", "Missed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="enterprises.enterprise",
                        verbose_name="enterprise",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical enterprise milestone",
                "verbose_name_plural": "historical enterprise milestones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="enterprise",
            index=models.Index(fields=["case", "-created_at"], name="enterprises_case_id_fa6b87_idx"),
        ),
        migrations.AddIndex(
            model_name="enterprise",
            index=models.Index(
                fields=["business_plan_status", "disbursement_date"], name="enterprises_busines_b8ce84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enterprise",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("grant_or_loan_amount__isnull", True), ("grant_or_loan_amount__gte", 0), _connector="OR"
                ),
                name="enterprise_support_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="enterprise",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("disbursement_date__isnull", True), ("grant_or_loan_amount__isnull", False), _connector="OR"
                ),
                name="enterprise_disbursement_needs_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="enterprise",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_on__isnull", True), models.Q(("closure_reason", ""), _negated=True), _connector="OR"
                ),
                name="enterprise_closure_needs_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="enterprisemilestone",
            index=models.Index(fields=["status", "target_date"], name="enterprises_status_5229ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="enterprisemilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ACHIEVED"), _negated=True), ("completion_date__isnull", False), _connector="OR"
                ),
                name="milestone_achieved_needs_date",
            ),
        ),
    ]
