# Generated by Django 5.2.17 on 2026-08-20 07:37

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_caseaction_index_names"),
        ("referrals", "0008_backfill_allowed_subject_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFollowUp",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                (
                    "attempt_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="attempt date"),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone call"),
                            ("SMS", "SMS"),
                            ("HOME_VISIT", "Home visit"),
                            ("OFFICE_VISIT", "Youth came to the office"),
                            ("PARTNER_VISIT", "Visit to the partner or employer"),
                            ("THIRD_PARTY", "Message left with a family member or official"),
                        ],
                        max_length=16,
                        verbose_name="contact method",
                    ),
                ),
                (
                    "contact_outcome",
                    models.CharField(
                        choices=[
                            ("REACHED_ENGAGED", "Reached — engaged"),
                            ("REACHED_NOT_ENGAGED", "Reached — not engaged"),
                            ("NO_RESPONSE", "No response"),
                            ("UNREACHABLE", "Unreachable"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="contact outcome",
                    ),
                ),
                (
                    "re_engagement_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_APPLICABLE", "Not applicable"),
                            ("AGREED", "Agreed to re-engage"),
                            ("CONSIDERING", "Considering"),
                            ("DECLINED", "Declined"),
                            ("UNABLE", "Willing but unable"),
                        ],
                        default="NOT_APPLICABLE",
                        max_length=16,
                        verbose_name="re-engagement",
                    ),
                ),
                (
                    "pathway_revision_flag",
                    models.BooleanField(
                        default=False,
                        help_text="The plan has to change. Raise the revision on the case; this only records the finding.",
                        verbose_name="pathway revision needed",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="conducted by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set when this contact verifies a specific referral outcome.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="related referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical follow-up",
                "verbose_name_plural": "historical follow-ups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "attempt_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="attempt date"),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone call"),
                            ("SMS", "SMS"),
                            ("HOME_VISIT", "Home visit"),
                            ("OFFICE_VISIT", "Youth came to the office"),
                            ("PARTNER_VISIT", "Visit to the partner or employer"),
                            ("THIRD_PARTY", "Message left with a family member or official"),
                        ],
                        max_length=16,
                        verbose_name="contact method",
                    ),
                ),
                (
                    "contact_outcome",
                    models.CharField(
                        choices=[
                            ("REACHED_ENGAGED", "Reached — engaged"),
                            ("REACHED_NOT_ENGAGED", "Reached — not engaged"),
                            ("NO_RESPONSE", "No response"),
                            ("UNREACHABLE", "Unreachable"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="contact outcome",
                    ),
                ),
                (
                    "re_engagement_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_APPLICABLE", "Not applicable"),
                            ("AGREED", "Agreed to re-engage"),
                            ("CONSIDERING", "Considering"),
                            ("DECLINED", "Declined"),
                            ("UNABLE", "Willing but unable"),
                        ],
                        default="NOT_APPLICABLE",
                        max_length=16,
                        verbose_name="re-engagement",
                    ),
                ),
                (
                    "pathway_revision_flag",
                    models.BooleanField(
                        default=False,
                        help_text="The plan has to change. Raise the revision on the case; this only records the finding.",
                        verbose_name="pathway revision needed",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="conducted by",
                    ),
                ),
                (
                    "related_referral",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this contact verifies a specific referral outcome.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="referrals.referral",
                        verbose_name="related referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "follow-up",
                "verbose_name_plural": "follow-ups",
                "ordering": ["-attempt_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["case", "-attempt_date"], name="followups_f_case_id_52ce3d_idx"),
                    models.Index(fields=["contact_outcome", "attempt_date"], name="followups_f_contact_2cd8c3_idx"),
                    models.Index(fields=["related_referral"], name="followups_f_related_d9280a_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("contact_outcome__in", ("REACHED_ENGAGED", "REACHED_NOT_ENGAGED")),
                            ("re_engagement_status__in", ["", "NOT_APPLICABLE"]),
                            _connector="OR",
                        ),
                        name="followup_reengagement_needs_contact",
                    )
                ],
            },
        ),
    ]
