# Generated by Django 5.2.17 on 2026-08-20 07:37

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_caseaction_index_names"),
        ("partners", "0002_historicalpartner_standing_partner_standing_and_more"),
        ("referrals", "0008_backfill_allowed_subject_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGrievance",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("woreda", models.CharField(db_index=True, max_length=128, verbose_name="woreda")),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("REFERRAL_QUALITY", "Referral quality or suitability"),
                            ("REFERRAL_DELAY", "Referral delay or no response"),
                            ("SERVICE_QUALITY", "Quality of the service received"),
                            ("STAFF_CONDUCT", "Staff conduct"),
                            ("SELECTION", "Selection or exclusion from the programme"),
                            ("PAYMENT", "Payment, stipend or grant"),
                            ("WORKPLACE", "Workplace conditions or treatment"),
                            ("SAFEGUARDING", "Safeguarding or harassment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                        verbose_name="complaint type",
                    ),
                ),
                (
                    "raised_by",
                    models.CharField(
                        choices=[
                            ("YOUTH", "Youth"),
                            ("EMPLOYER", "Employer"),
                            ("TRAINER", "Trainer"),
                            ("PARTNER", "Partner organisation"),
                        ],
                        max_length=16,
                        verbose_name="raised by",
                    ),
                ),
                (
                    "complainant_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional. A complaint may be made anonymously and is still recorded.",
                        max_length=255,
                        verbose_name="complainant",
                    ),
                ),
                ("complainant_contact", models.CharField(blank=True, max_length=64, verbose_name="contact")),
                ("summary", models.TextField(verbose_name="what happened")),
                (
                    "date_raised",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="date raised"),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed without resolution"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("resolution_date", models.DateField(blank=True, null=True, verbose_name="resolution date")),
                ("resolution_notes", models.TextField(blank=True, verbose_name="resolution notes")),
                (
                    "referral_quality_feedback_flag",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marks a complaint about referral quality or timeliness. Read by the partner performance panel.",
                        verbose_name="referral quality feedback",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "about_partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="partners.partner",
                        verbose_name="about partner",
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional. A complaint may come from somebody who is not on the register.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "related_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="related referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical grievance",
                "verbose_name_plural": "historical grievances",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Grievance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("woreda", models.CharField(db_index=True, max_length=128, verbose_name="woreda")),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("REFERRAL_QUALITY", "Referral quality or suitability"),
                            ("REFERRAL_DELAY", "Referral delay or no response"),
                            ("SERVICE_QUALITY", "Quality of the service received"),
                            ("STAFF_CONDUCT", "Staff conduct"),
                            ("SELECTION", "Selection or exclusion from the programme"),
                            ("PAYMENT", "Payment, stipend or grant"),
                            ("WORKPLACE", "Workplace conditions or treatment"),
                            ("SAFEGUARDING", "Safeguarding or harassment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                        verbose_name="complaint type",
                    ),
                ),
                (
                    "raised_by",
                    models.CharField(
                        choices=[
                            ("YOUTH", "Youth"),
                            ("EMPLOYER", "Employer"),
                            ("TRAINER", "Trainer"),
                            ("PARTNER", "Partner organisation"),
                        ],
                        max_length=16,
                        verbose_name="raised by",
                    ),
                ),
                (
                    "complainant_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional. A complaint may be made anonymously and is still recorded.",
                        max_length=255,
                        verbose_name="complainant",
                    ),
                ),
                ("complainant_contact", models.CharField(blank=True, max_length=64, verbose_name="contact")),
                ("summary", models.TextField(verbose_name="what happened")),
                (
                    "date_raised",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="date raised"),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed without resolution"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("resolution_date", models.DateField(blank=True, null=True, verbose_name="resolution date")),
                ("resolution_notes", models.TextField(blank=True, verbose_name="resolution notes")),
                (
                    "referral_quality_feedback_flag",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marks a complaint about referral quality or timeliness. Read by the partner performance panel.",
                        verbose_name="referral quality feedback",
                    ),
                ),
                (
                    "about_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grievances",
                        to="partners.partner",
                        verbose_name="about partner",
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_grievances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. A complaint may come from somebody who is not on the register.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievances",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_grievances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "related_referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievances",
                        to="referrals.referral",
                        verbose_name="related referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "grievance",
                "verbose_name_plural": "grievances",
                "ordering": ["-date_raised", "-created_at"],
                "indexes": [
                    models.Index(fields=["resolution_status", "date_raised"], name="grievances__resolut_949ef9_idx"),
                    models.Index(fields=["woreda", "resolution_status"], name="grievances__woreda_049f36_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("resolution_status__in", ("RESOLVED", "CLOSED")), _negated=True),
                            ("resolution_date__isnull", False),
                            _connector="OR",
                        ),
                        name="grievance_closed_needs_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("resolution_status", "RESOLVED"), _negated=True),
                            models.Q(("resolution_notes", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="grievance_resolved_needs_notes",
                    ),
                ],
            },
        ),
    ]
