# Generated by Django 5.2.17 on 2026-08-20 06:19

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_caseaction_index_names"),
        ("partners", "0002_historicalpartner_standing_partner_standing_and_more"),
        ("referrals", "0008_backfill_allowed_subject_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTrainingEnrolment",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("LIFE_SKILLS", "Life skills and employability"),
                            ("TVET", "Technical and vocational (TVET)"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="training type",
                    ),
                ),
                (
                    "trade_or_skill_area",
                    models.CharField(
                        blank=True,
                        help_text="TVET only — the trade the course teaches.",
                        max_length=128,
                        verbose_name="trade or skill area",
                    ),
                ),
                (
                    "enrolment_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="enrolment date"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Scheduled end. The actual end is the completion date.", verbose_name="end date"
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Share of sessions attended, where the provider records it.",
                        max_digits=5,
                        null=True,
                        verbose_name="attendance rate (%)",
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Enrolled"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED_OUT", "Dropped out"),
                            ("FAILED_ASSESSMENT", "Failed assessment"),
                        ],
                        db_index=True,
                        default="ENROLLED",
                        max_length=24,
                        verbose_name="completion status",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="completion date"),
                ),
                ("assessment_result", models.CharField(blank=True, max_length=255, verbose_name="assessment result")),
                (
                    "certificate_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_APPLICABLE", "Not applicable"),
                            ("PENDING", "Pending"),
                            ("AWARDED", "Awarded"),
                            ("COLLECTED", "Collected by the youth"),
                            ("WITHHELD", "Withheld"),
                        ],
                        default="NOT_APPLICABLE",
                        max_length=24,
                        verbose_name="certificate status",
                    ),
                ),
                ("dropout_flag", models.BooleanField(default=False, editable=False, verbose_name="dropped out")),
                ("dropout_date", models.DateField(blank=True, null=True, verbose_name="dropout date")),
                ("dropout_reason", models.TextField(blank=True, verbose_name="dropout reason")),
                (
                    "triggers_onward_referral",
                    models.BooleanField(default=False, editable=False, verbose_name="triggers an onward referral"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onward_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The referral raised after this training completed, once a case manager confirms the prompt.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="onward referral",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The trainer or case manager who entered this record. Scopes a trainer's own caseload.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "source_referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The referral that placed the youth into this training, where one did.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="referrals.referral",
                        verbose_name="source referral",
                    ),
                ),
                (
                    "training_provider",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="partners.partner",
                        verbose_name="training provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical training enrolment",
                "verbose_name_plural": "historical training enrolments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TrainingEnrolment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("LIFE_SKILLS", "Life skills and employability"),
                            ("TVET", "Technical and vocational (TVET)"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="training type",
                    ),
                ),
                (
                    "trade_or_skill_area",
                    models.CharField(
                        blank=True,
                        help_text="TVET only — the trade the course teaches.",
                        max_length=128,
                        verbose_name="trade or skill area",
                    ),
                ),
                (
                    "enrolment_date",
                    models.DateField(db_index=True, default=datetime.date.today, verbose_name="enrolment date"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Scheduled end. The actual end is the completion date.", verbose_name="end date"
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Share of sessions attended, where the provider records it.",
                        max_digits=5,
                        null=True,
                        verbose_name="attendance rate (%)",
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Enrolled"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED_OUT", "Dropped out"),
                            ("FAILED_ASSESSMENT", "Failed assessment"),
                        ],
                        db_index=True,
                        default="ENROLLED",
                        max_length=24,
                        verbose_name="completion status",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="completion date"),
                ),
                ("assessment_result", models.CharField(blank=True, max_length=255, verbose_name="assessment result")),
                (
                    "certificate_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_APPLICABLE", "Not applicable"),
                            ("PENDING", "Pending"),
                            ("AWARDED", "Awarded"),
                            ("COLLECTED", "Collected by the youth"),
                            ("WITHHELD", "Withheld"),
                        ],
                        default="NOT_APPLICABLE",
                        max_length=24,
                        verbose_name="certificate status",
                    ),
                ),
                ("dropout_flag", models.BooleanField(default=False, editable=False, verbose_name="dropped out")),
                ("dropout_date", models.DateField(blank=True, null=True, verbose_name="dropout date")),
                ("dropout_reason", models.TextField(blank=True, verbose_name="dropout reason")),
                (
                    "triggers_onward_referral",
                    models.BooleanField(default=False, editable=False, verbose_name="triggers an onward referral"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrolments",
                        to="cases.case",
                        verbose_name="case",
                    ),
                ),
                (
                    "onward_referral",
                    models.ForeignKey(
                        blank=True,
                        help_text="The referral raised after this training completed, once a case manager confirms the prompt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preceding_training",
                        to="referrals.referral",
                        verbose_name="onward referral",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="The trainer or case manager who entered this record. Scopes a trainer's own caseload.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_training_enrolments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "source_referral",
                    models.ForeignKey(
                        blank=True,
                        help_text="The referral that placed the youth into this training, where one did.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_enrolments",
                        to="referrals.referral",
                        verbose_name="source referral",
                    ),
                ),
                (
                    "training_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_enrolments",
                        to="partners.partner",
                        verbose_name="training provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "training enrolment",
                "verbose_name_plural": "training enrolments",
                "ordering": ["-enrolment_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["case", "-enrolment_date"], name="training_tr_case_id_a95f91_idx"),
                    models.Index(fields=["completion_status", "training_type"], name="training_tr_complet_27b4d7_idx"),
                    models.Index(
                        fields=["training_provider", "completion_status"], name="training_tr_trainin_870954_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))), name="training_end_after_start"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completion_status", "COMPLETED"), _negated=True),
                            ("completion_date__isnull", False),
                            _connector="OR",
                        ),
                        name="training_completed_needs_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completion_status", "DROPPED_OUT"), _negated=True),
                            ("dropout_date__isnull", False),
                            _connector="OR",
                        ),
                        name="training_dropout_needs_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("attendance_rate__isnull", True),
                            models.Q(("attendance_rate__gte", 0), ("attendance_rate__lte", 100)),
                            _connector="OR",
                        ),
                        name="training_attendance_rate_range",
                    ),
                ],
            },
        ),
    ]
