# Generated by Django 5.2.17 on 2026-08-11 02:32

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPartner",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("partner_name", models.CharField(db_index=True, max_length=255, verbose_name="partner name")),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("TVET_INSTITUTION", "TVET Institution"),
                            ("EMPLOYER", "Employer"),
                            ("ENTERPRISE_DEVELOPMENT_AGENCY", "Enterprise Development Agency"),
                            ("SAVINGS_GROUP", "Savings Group"),
                            ("HEALTH_SERVICE", "Health Service"),
                            ("PSYCHOSOCIAL_SERVICE", "Psychosocial Service"),
                            ("LEGAL_AID", "Legal Aid"),
                            ("FINANCE_INSTITUTION", "Finance Institution"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="partner type",
                    ),
                ),
                (
                    "woreda_coverage",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        default=list,
                        help_text="Woredas this partner serves.",
                        size=None,
                        verbose_name="woreda coverage",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255, verbose_name="contact name")),
                ("phone", models.CharField(max_length=32, verbose_name="phone")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "active_status",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive partners cannot receive new referrals but keep their history.",
                        verbose_name="active",
                    ),
                ),
                (
                    "mou_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "No MOU"),
                            ("DRAFT", "Draft"),
                            ("SIGNED", "Signed"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="NONE",
                        max_length=16,
                        verbose_name="MOU status",
                    ),
                ),
                ("mou_date", models.DateField(blank=True, null=True, verbose_name="MOU date")),
                (
                    "performance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Qualitative input alongside the quantitative referral performance dashboard (spec §8).",
                        verbose_name="performance notes",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical partner",
                "verbose_name_plural": "historical partners",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("partner_name", models.CharField(db_index=True, max_length=255, verbose_name="partner name")),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("TVET_INSTITUTION", "TVET Institution"),
                            ("EMPLOYER", "Employer"),
                            ("ENTERPRISE_DEVELOPMENT_AGENCY", "Enterprise Development Agency"),
                            ("SAVINGS_GROUP", "Savings Group"),
                            ("HEALTH_SERVICE", "Health Service"),
                            ("PSYCHOSOCIAL_SERVICE", "Psychosocial Service"),
                            ("LEGAL_AID", "Legal Aid"),
                            ("FINANCE_INSTITUTION", "Finance Institution"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="partner type",
                    ),
                ),
                (
                    "woreda_coverage",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        default=list,
                        help_text="Woredas this partner serves.",
                        size=None,
                        verbose_name="woreda coverage",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255, verbose_name="contact name")),
                ("phone", models.CharField(max_length=32, verbose_name="phone")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "active_status",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive partners cannot receive new referrals but keep their history.",
                        verbose_name="active",
                    ),
                ),
                (
                    "mou_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "No MOU"),
                            ("DRAFT", "Draft"),
                            ("SIGNED", "Signed"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="NONE",
                        max_length=16,
                        verbose_name="MOU status",
                    ),
                ),
                ("mou_date", models.DateField(blank=True, null=True, verbose_name="MOU date")),
                (
                    "performance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Qualitative input alongside the quantitative referral performance dashboard (spec §8).",
                        verbose_name="performance notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner",
                "verbose_name_plural": "partners",
                "ordering": ["partner_name"],
                "indexes": [
                    models.Index(fields=["partner_type", "active_status"], name="partners_pa_partner_ed28bf_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner_name", "partner_type"), name="unique_partner_name_per_type"
                    )
                ],
            },
        ),
    ]
