# Generated by Django 5.2.17 on 2026-08-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpartner",
            name="standing",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("BLACKLISTED", "Blacklisted")],
                db_index=True,
                default="ACTIVE",
                help_text="Suspended or blacklisted organisations cannot be proposed for new referrals or linkages.",
                max_length=16,
                verbose_name="standing",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="standing",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("BLACKLISTED", "Blacklisted")],
                db_index=True,
                default="ACTIVE",
                help_text="Suspended or blacklisted organisations cannot be proposed for new referrals or linkages.",
                max_length=16,
                verbose_name="standing",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpartner",
            name="partner_type",
            field=models.CharField(
                choices=[
                    ("TVET_INSTITUTION", "TVET Institution"),
                    ("EMPLOYER", "Employer"),
                    ("ENTERPRISE_DEVELOPMENT_AGENCY", "Enterprise Development Agency"),
                    ("SAVINGS_GROUP", "Savings Group"),
                    ("HEALTH_SERVICE", "Health Service"),
                    ("PSYCHOSOCIAL_SERVICE", "Psychosocial Service"),
                    ("LEGAL_AID", "Legal Aid"),
                    ("FINANCE_INSTITUTION", "Finance Institution"),
                    ("RUSACCO", "RUSACCO (rural savings and credit cooperative)"),
                    ("COOPERATIVE", "Cooperative"),
                    ("BUYER", "Buyer / offtaker"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="partner type",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_type",
            field=models.CharField(
                choices=[
                    ("TVET_INSTITUTION", "TVET Institution"),
                    ("EMPLOYER", "Employer"),
                    ("ENTERPRISE_DEVELOPMENT_AGENCY", "Enterprise Development Agency"),
                    ("SAVINGS_GROUP", "Savings Group"),
                    ("HEALTH_SERVICE", "Health Service"),
                    ("PSYCHOSOCIAL_SERVICE", "Psychosocial Service"),
                    ("LEGAL_AID", "Legal Aid"),
                    ("FINANCE_INSTITUTION", "Finance Institution"),
                    ("RUSACCO", "RUSACCO (rural savings and credit cooperative)"),
                    ("COOPERATIVE", "Cooperative"),
                    ("BUYER", "Buyer / offtaker"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="partner type",
            ),
        ),
    ]
