# Generated by Django 5.2.17 on 2026-08-11 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Stable identifier, e.g. ET-OR-ES-ADAMA. Used by imports and external systems.",
                        max_length=32,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "level",
                    models.CharField(
                        choices=[("REGION", "Region"), ("ZONE", "Zone"), ("WOREDA", "Woreda"), ("KEBELE", "Kebele")],
                        db_index=True,
                        max_length=8,
                        verbose_name="level",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate rather than delete: existing records reference this name.",
                        verbose_name="active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.location",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
                "ordering": ["level", "name"],
                "indexes": [models.Index(fields=["level", "is_active"], name="locations_l_level_2917f2_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("parent", "name", "level"), name="unique_location_within_parent")
                ],
            },
        ),
    ]
